### ISSUE TITLE
Remote: Iteration Plan for August 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#10142]
This plan captures our Remote work in **August 2024**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22August+2024%22). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark | Description                                       |
| ---- | ------------------------------------------------- |
| 🏃‍♀️   | work in progress                                  |
| ✋   | blocked task                                      |
| 💪   | stretch goal for this iteration                   |
| 🔴   | missing issue reference                           |
| 🔵   | more investigation required to remove uncertainty |
| ⚫   | under discussion within the team                  |
| ⬛   | a large work item, larger than one iteration      |

</details>

### General
- [x] Provide Windows ARM64 server [vscode#221755](https://github.com/microsoft/vscode/issues/221755) @deepak1556

### Dev Container Specification / CLI
- [x] Proposal: Template `optionalPaths` property [devcontainers/spec#484](https://github.com/devcontainers/spec/pull/484) @joshspicer 

### Dev Containers Extension
- [x] Doc improvements [vscode-docs#7458](https://github.com/microsoft/vscode-docs/issues/7458) @bamurtaugh 

### SSH Extension
- [x] Remote Explorer improvements [vscode-remote-release#7144](https://github.com/microsoft/vscode-remote-release/issues/7144), [vscode-remote-release#8034](https://github.com/microsoft/vscode-remote-release/issues/8034) @joshspicer
- [x] Setup improvements [vscode-remote-release#5603](https://github.com/microsoft/vscode-remote-release/issues/5603), [vscode-remote-release#1747](https://github.com/microsoft/vscode-remote-release/issues/1747) @joshspicer

### Remote Repositories
- [x] Improvements to the GitHub Repositories extension (see [issues](https://github.com/microsoft/vscode-remote-repositories-github/issues?q=is%3Aissue+milestone%3A%22August+2024%22)) @joyceerhl

---
### Deferred
- None.

**Comment by Adnanmnsour** [comment]
> This plan captures our Remote work in **August 2024**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22August+2024%22). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.
> 
> ## Plan Items
> Below is a summary of the top level plan items.
> 
> Legend of annotations
> ### General
> * [x]  Provide Windows ARM64 server [vscode#221755](https://github.com/microsoft/vscode/issues/221755) @deepak1556
> 
> ### Dev Container Specification / CLI
> * [x]  Proposal: Template `optionalPaths` property [devcontainers/spec#484](https://github.com/devcontainers/spec/pull/484) @joshspicer
> 
> ### Dev Containers Extension
> * [x]  Doc improvements [vscode-docs#7458](https://github.com/microsoft/vscode-docs/issues/7458) @bamurtaugh
> 
> ### SSH Extension
> * [x]  Remote Explorer improvements [vscode-remote-release#7144](https://github.com/microsoft/vscode-remote-release/issues/7144), [vscode-remote-release#8034](https://github.com/microsoft/vscode-remote-release/issues/8034) @joshspicer
> * [ ]  🏃 Setup improvements [vscode-remote-release#5603](https://github.com/microsoft/vscode-remote-release/issues/5603), [vscode-remote-release#1747](https://github.com/microsoft/vscode-remote-release/issues/1747) @joshspicer
> 
> ### Remote Repositories
> * [ ]  🏃 Improvements to the GitHub Repositories extension (see [issues](https://github.com/microsoft/vscode-remote-repositories-github/issues?q=is%3Aissue+milestone%3A%22August+2024%22)) @joyceerhl
> 
> ### Deferred
> * None.
