### ISSUE TITLE
Remote: Iteration Plan for August 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#1135]
This plan captures our work on the Remote development extensions in **August**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/78844). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote - Core
- [x] Generalize SSH explorer to allow contributions from Containers and WSL https://github.com/microsoft/vscode-remote-release/issues/926 @rebornix
- [x] Polish reconnect dialog / UX https://github.com/microsoft/vscode-remote-release/issues/1246 @sbatten 
- [x] Ensure VS Code server doesn't listen on 0.0.0.0 https://github.com/microsoft/vscode-remote-release/issues/1016 @roblourens @alexandrudima
- [x] Improve connection/reconnection reliability https://github.com/microsoft/vscode-remote-release/issues/955 @alexandrudima
- [x] Improve discoverability of the 'install local extensions' command https://github.com/microsoft/vscode-remote-release/issues/1066 @sandy081
- [x] Create ARM64 server builds @joaomoreno
- [ ] Polish extension readme files @chrisdias @sana-ajani @bowdenk7 @gregvanl @chuxel

### Remote - SSH
- [x] Enable dynamic forwarding out of the box https://github.com/microsoft/vscode-remote-release/issues/1157 @roblourens
- [x] Support installing the VS Code server through the VS Code client https://github.com/microsoft/vscode-remote-release/issues/15 @roblourens
- [x] Explore how to prevent passphrase and password prompts to appear behind the reconnect dialog https://github.com/microsoft/vscode-remote-release/issues/1072 @roblourens @sbatten
- [x] Automatically enable SSH agent forwarding if needed https://github.com/microsoft/vscode-remote-release/issues/1158 @roblourens
- [x] Support connection sharing between windows that connect to the same host https://github.com/microsoft/vscode-remote-release/issues/96 @roblourens
- [x] Adopt ARM64 support https://github.com/microsoft/vscode-remote-release/issues/69 @roblourens
- [ ] :runner: SSH Blog post series @sana-ajani @gregvanl

### Remote - Containers
- [x] Add command 'Open Workspace in Container', 'Reopen Workspace in Container' https://github.com/microsoft/vscode-remote-release/issues/387 @chrmarti @aeschli
- [x] More guidance in `devcontainer.json` when reusing an existing Docker Compose / Dockerfile https://github.com/microsoft/vscode-remote-release/issues/1076 @chrmarti
- [x] Investigate: Reducing reliance on `runArgs` for common scenarios: mount points, environment variables https://github.com/microsoft/vscode-remote-release/issues/1201 @chrmarti
- [x] Contribute to Remote Explorer https://github.com/microsoft/vscode-remote-release/issues/1141 @alexr00
- [ ] :runner: Prompt to rebuild on reload if `devcontainer.json` or associated Dockerfile/compose files have been updated https://github.com/microsoft/vscode-remote-release/issues/758 @chrmarti
- [x] Support `${localWorkspaceFolder}` in `devcontainer.json` https://github.com/microsoft/vscode-remote-release/issues/442 @chrmarti
- [ ] Support all `docker` related settings provided by the `Docker` extension https://github.com/microsoft/vscode-remote-release/issues/859
- [ ] :runner: Container Blog post series @bowdenk7 @gregvanl

### Remote - WSL
- [x] WSL Blog post series Part III @gregvanl
- [ ] :runner: WSL2 Blog post @fiveisprime @gregvanl

-------
### Deferred Items
- :red_circle: :muscle: Support to debug the local and remote Extension Host at the same time @weinand

**Comment by jabbera** [comment]
Hi all! Thanks for the amazing extension. 

Any chance of getting: https://github.com/microsoft/vscode-remote-release/issues/1045 

It’s very annoying to have to manage 2 docker files for each solution.
