### ISSUE TITLE
Remote Explorer - Container contribution polish

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#1382]
- [x] Guide user to create first container when none exists #1349 
- [x] Add 'Rebuild Container' to the container's context menu #1342
- [x] Improve icons #1289
- [x] Group the information items under a common node 'Attributes'
![image](https://user-images.githubusercontent.com/172399/64488591-1730d580-d24a-11e9-8d23-70bba8538578.png)
- [x] Add context menu item for click actions (e.g. open dev container on Container item)
- [x] Provide 'Inspect' actions for Docker objects (Container, Image, Volume), opens JSON file with corresponding inspect output
- [x] Contribute actions to the view's action bar (refresh, connect)
- [x] Details view title shows the name of the container for which the details are shown. Depends on https://github.com/microsoft/vscode/issues/80208

**Comment by alexr00** [comment]
Refresh in the view's action bar should never be needed since we listen for docker events (If it's needed then there's something wrong with how we're listening to events). For consistency I can add it though.
