### ISSUE TITLE
Remote: Iteration Plan for September 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#1390]
This plan captures our work on the Remote development extensions in **September**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/80591). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote - Core
- [x] Polish behavior of the Remote Explorer (labels, section expand state) https://github.com/microsoft/vscode-remote-release/issues/1426 @roblourens
- [x] Investigate opening a remote workspace from the command line https://github.com/microsoft/vscode-remote-release/issues/585 @aeschli
- [x] Activate UI extensions installed into a remote VS Code Server https://github.com/microsoft/vscode-remote-release/issues/1400 @alexandrudima

### Remote - SSH
- [x] Support connection sharing between windows that connect to the same host https://github.com/microsoft/vscode-remote-release/issues/96 @roblourens
- [x] Improve error messages when target platforms don't match minimal requirements https://github.com/microsoft/vscode-remote-release/issues/1427 @roblourens
- [x] Explore fusing the SSH explorer extension with the SSH core extension https://github.com/microsoft/vscode-remote-release/issues/1428 @roblourens
- [x] Support the VS Code Server on Windows in Insiders https://github.com/microsoft/vscode-remote-release/issues/25 @roblourens
- [x] SSH Blog post series @sana-ajani @gregvanl

### Remote - Containers
- [x] Improve 'Attach to Running Container' support https://github.com/microsoft/vscode-remote-release/issues/1383 @chrmarti
- [x] Support to open/clone a repository into a volume https://github.com/microsoft/vscode-remote-release/issues/1395 @egamma @chrmarti
- [x] Prompt to rebuild on reload if `devcontainer.json` or associated Dockerfile/compose files have been updated https://github.com/microsoft/vscode-remote-release/issues/758 @chrmarti
- [x] Support all `docker` related settings provided by the `Docker` extension https://github.com/microsoft/vscode-remote-release/issues/859 @chrmarti
- [x] Polish Remote explorer contribution https://github.com/microsoft/vscode-remote-release/issues/1382 @alexr00
- [ ] :runner: Support 'ServerReady' for containers https://github.com/microsoft/vscode-remote-release/issues/1115 @weinand
- [x] Alpine container definitions https://github.com/microsoft/vscode-dev-containers/pull/126 @chuxel
- [ ] :runner: Container Blog post series @bowdenk7 @gregvanl

### Remote - WSL
- [x] Contribute to remote explorer (installed distro, recents) https://github.com/microsoft/vscode-remote-release/issues/1142 @alexr00 @aeschli
- [x] Continued WSL2 fixes as they come up @aeschli
- [x] Investigate WSL2 and Docker extension https://github.com/microsoft/vscode-docker/issues/1199 @fiveisprime
- [x] Investigate Remote - Containers and WSL2 https://github.com/microsoft/vscode-remote-release/issues/1089 @chuxel
- [ ] :runner: Add VS Code + Remote WSL extension in Windows/WSL 2 docs @fiveisprime

-------
### Deferred Items
- Investigate: Reducing reliance on `runArgs` for common scenarios: mount points, environment variables https://github.com/microsoft/vscode-remote-release/issues/1201 @chrmarti
- WSL2 + Docker Blog post @fiveisprime @gregvanl
- :red_circle: :muscle: Support to debug the local and remote Extension Host at the same time @weinand
- :red_circle: :muscle: Investigate automatic port forwarding based on console output https://github.com/microsoft/vscode-remote-release/issues/1439 @weinand

**Comment by bhack** [comment]
Any space for the top 2 issue n the Containers section?
https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3Acontainers

**Comment by pwwang** [comment]
Any workaround for centos6 servers without root privileges?
A lot of users encountered this and suffered from it. #103

**Comment by bhack** [comment]
This issue now is the [2nd most upvoted](https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc+label%3Acontainers) feature request in the container subcomponent/label.
I hope it will start to join in the imminent October roadmap cycle ticket.
