### ISSUE TITLE
Remote: Iteration Plan for November 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#1775]
This plan captures our work on the Remote development extensions in **November**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/83930). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote - Core
- [x] Revisit the Remote Explorer layout to better support different remote types https://github.com/microsoft/vscode-remote-release/issues/1778 @alexr00
- [ ] :runner: Provide common UI for port forwarding https://github.com/microsoft/vscode-remote-release/issues/1777 @alexr00

### Remote - SSH
None.

### Remote - Containers
- [x] Improve provisioning and startup performance of a dev container https://github.com/microsoft/vscode-remote-release/issues/1823 @chrmarti
- [x] Investigate support to install extensions into a named volume https://github.com/microsoft/vscode-remote-release/issues/421 @chrmarti
- [x] Investigate: Reducing reliance on `runArgs` for common scenarios: mount points, environment variables https://github.com/microsoft/vscode-remote-release/issues/1201 @chrmarti
- [x] Investigate supporting user/group id as configuration option https://github.com/microsoft/vscode-remote-release/issues/1155 @chrmarti
- [x] Support `settings` property in attached config files https://github.com/microsoft/vscode-remote-release/issues/1589 @chrmarti
- [x] Permit use of Remote Container using SSH transport https://github.com/microsoft/vscode-remote-release/issues/636 @chrmarti
- [x] Investigate pre-building a subset of `vscode-dev-containers` to speed up first time experiences https://github.com/microsoft/vscode-dev-containers/issues/140 @chuxel - Investigation done, next is completing implementation.
- [x] Open repository in container - support more than one container for a repository https://github.com/microsoft/vscode-remote-release/issues/1581 @egamma
- [x] Include guidance for how to use Remote Containers as a sandbox for multiple projects/folders ([new quick start](https://code.visualstudio.com/docs/remote/containers#_quick-start-configure-a-sandbox-for-multiple-projects-or-folders)) @chuxel
- [x] Container Blog post series @bowdenk7 @gregvanl

### Remote - WSL
- [ ] :runner: WSL2 + Docker Blog post @fiveisprime @gregvanl
- [x] Add VS Code + Remote WSL extension in Windows/WSL 2 docs @fiveisprime

-------
### Deferred Items
- :runner: Open repository in container - support private repositories  (private repos, more flexible volume usage) https://github.com/microsoft/vscode-remote-release/issues/1578 @egamma @chrmarti
- Adopt common port forwarding UI in Remote-SSH @roblourens
- Adopt common port forwarding UI in Remote-Containers @chrmarti

**Comment by bhack** [comment]
Please add some kind of initial Kubernetes support https://github.com/microsoft/vscode-remote-release/issues/12. 
Community cannot contribute to this close source plugin. So please evaliate that as the top feature requested with the container label (other than podman).

**Comment by Dijir** [comment]
It would be interesting to have the Remote - Containers extension available for Remote WSL.
Thus the extension would make use of the wsl2 virtual machine docker itself, greatly improving the processing speed of the files that already are on the vm.

**Comment by chrmarti** [comment]
@Dijir Remote-Containers should already show the WSL2 containers. Could you open an issue if that doesn't work?
