### ISSUE TITLE
Documentation update for Remote-Containers

### ISSUE THREAD

**Issue by chrmarti** [microsoft/vscode-remote-release#1923]
Collecting changes affecting documentation:
- [x] ARM32 and ARM64 support. https://github.com/microsoft/vscode-remote-release/issues/1716
- [x] SSH agent forwarding. https://github.com/microsoft/vscode-remote-release/issues/106#issuecomment-558494074
- [x] Extensions folder can be mounted direct. https://github.com/microsoft/vscode-remote-release/issues/421#issuecomment-559716606
- [x] Sample repositories' READMEs need to be updated to reflect that `Try Sample...` now opens the repository using a volume. (E.g.: https://github.com/microsoft/vscode-remote-try-node)

Will add more as I come across them.

**Comment by Chuxel** [comment]
Others:
- [ ] Updated use of `remoteEnv`, `containerEnv` for env vars (affects lots of places) over runArgs
- [ ] Recommend `remoteUser`, `containerUser` over runArgs. Recommend `remoteUser` over modifying Docker Compose files.
- [x] Update vscode-dev-containers to use new properties
- [ ] Update extension READMEs for platform support (Remote - Containers, Remote Development extension pack)
- [ ] Update sample projects to use new properties (possibly holding on https://github.com/MicrosoftDocs/vsonline/issues/247 to avoid confusing people).

**Comment by Chuxel** [comment]
Docs updates are getting staged here: https://github.com/microsoft/vscode-docs/tree/clantz/1.41-updates

**Comment by Chuxel** [comment]
Sample updates are prepped in branches called `clantz/1.41` - I won't merge until 1.41 ships to avoid confusion.

**Comment by Chuxel** [comment]
Closing since the last step is just to merge samples.
