### ISSUE TITLE
Remote: Iteration Plan for January 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#2075]
This plan captures our work on the Remote development extensions in **January**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/87479). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote - Core
- [x] Provide common UI for port forwarding (finish API, persisting of forwarded ports per workspace) https://github.com/microsoft/vscode-remote-release/issues/1777 @alexr00
- [x] :red_circle: Investigate improving reconnect behaviour @alexdima @sbatten
- [x] Improve case-sensitivity for file system providers https://github.com/microsoft/vscode/issues/48258 @isidorn
- [x] Improve downloading and uploading of files https://github.com/microsoft/vscode-remote-release/issues/1839 https://github.com/microsoft/vscode-remote-release/issues/1840 https://github.com/microsoft/vscode-remote-release/issues/1149 https://github.com/microsoft/vscode-remote-release/issues/1851 @isidorn

### Remote - SSH
- [x] Adopt common port forwarding UI in Remote-SSH https://github.com/microsoft/vscode-remote-release/issues/2077 @roblourens
- [x] Productize support for Remote server support on Windows https://github.com/microsoft/vscode-remote-release/issues/25 @roblourens

### Remote - Containers
- [x] Open repository in container - support private repositories  (private repos, more flexible volume usage) https://github.com/microsoft/vscode-remote-release/issues/1578 @chrmarti @chuxel
- [x] Adopt common port forwarding UI in Remote-Containers @alexr00
- [x] Simplify adding extensions to the `devContainer.json`: Provide Intellisense and validations for the `extensions` section https://github.com/microsoft/vscode-remote-release/issues/1800 @chrmarti
- [x] Explore dotfiles repositories https://dotfiles.github.io/ https://github.com/microsoft/vscode-remote-release/issues/2153 @chrmarti
- [x] Improve the experience when user is iteratively developing a devcontainer's Dockerfile and the building fails. Provide access to the last log, make reopen locally a primary action) https://github.com/microsoft/vscode-remote-release/issues/1125 @chrmarti
- [x] Add 'Rebuild and Reopen in Container'Â https://github.com/microsoft/vscode-remote-release/issues/1750 @chrmarti
- [x] Investigate `.devcontainer` support for the VS Code repo https://github.com/microsoft/vscode-remote-release/issues/2154 @chrmarti
- [x] Introduce a `forwardPorts` property to reduce port conflicts https://github.com/microsoft/vscode-remote-release/issues/1009, https://github.com/microsoft/vscode-remote-release/issues/1809 @chrmarti
- [x] Complete roll out of first set of pre-built `vscode-dev-containers` images speed up first time experiences https://github.com/microsoft/vscode-dev-containers/issues/140 @chuxel

### Remote - WSL
- [x] Support 'Reveal in Explorer' https://github.com/microsoft/vscode-remote-release/issues/1659 @aeschli
- [x] Explore: Allow piping to `stdin` https://github.com/microsoft/vscode-remote-release/issues/1764 @aeschli

-----
### Deferred Items
- Explore using the git installed on Windows  https://github.com/microsoft/vscode-remote-release/issues/1844 @aeschli

**Comment by bhack** [comment]
Please give some sense to the community top upvoted priorities in containers section:
https://github.com/microsoft/vscode-remote-release/issues?q=is%3Aopen+label%3Acontainers+sort%3Areactions-%2B1-desc

**Comment by imba-tjd** [comment]
I have the same issue of `Allow piping to stdin #1764` using **Remote - SSH**

**Comment by Chuxel** [comment]
@bhack We've been away for the holidays, but now that we're back I wanted to briefly mention that the draft 2020 roadmap for VS Code was published before the holidays which includes Kubernetes investigations (along with [macOS](https://github.com/microsoft/vscode-remote-release/issues/24#issuecomment-555695073) which is the top one today). See the [VS Code Roadmap](https://github.com/microsoft/vscode/wiki/Roadmap) and [Remote Roadmap](https://github.com/microsoft/vscode-remote-release/wiki/Roadmap) drafts.
 
For a bit of insight, here’s a how we’re thinking about new platforms: For existing platforms, we know that lots little or medium sized issues can cause major problems for something you use every day. We don’t want to let the community down, so we want to be sure we’re in good shape on existing supported platforms before moving onto the next one. When the product is at that point is primarily driven by community feedback - particularly the 2000+ issues that have been logged here. Each platform we’ve added has had its own unique challenges, even for something as consistent as SSH, and we know Kubernetes is going to be bigger change particularly given we try to cater to people running any of the three major platforms locally (Linux, macOS, and Windows). For SSH, we started with server operating systems, and containers we started with Docker - so while we haven’t picked them up quite yet, macOS and Kubernetes were explicitly called out on the roadmap given community interest.
 
Also, if anyone is interested in the planning process, the VS Code Remote Development extensions use the same [process as VS Code](https://github.com/microsoft/vscode/wiki/Development-Process). As with the microsoft/vscode repo, once we understand an issue, we watch :+1: reactions across issues to understand interest rather than individual responses due to the sheer volume of them that comes across between the two repos. We absolutely hear the feedback and definitely appreciate the upvoting - it really does help!

**Comment by bhack** [comment]
@Chuxel We cannot help you to achieve this Roadmap faster. It Is the downside of the full closed source strategy on this extension. 
So It Is totally out of our control how many resources you can allocate on this extension we can just ask you to schedule incremental over most popular upvoted feature. If they are too big you can just approach to these incrementally as you have done to the other core features.

**Comment by Coderx7** [comment]
Please add offline support for completely offline/behind firewall systems (both host and the remote) #2176  
The current situation assumes, the host has access to internet but this shouldnt be. at least providing an offline package with all the dependencies would be great (just like how the [cpptools extension](https://github.com/microsoft/vscode-cpptools/) does it) 
Thank you all very much for all of this.

**Comment by Lastwisher** [comment]
Also there this one one of highest voted feature request and its fairly simple one 

https://github.com/microsoft/vscode-remote-release/issues/222

Just need a option for argument
