### ISSUE TITLE
Remote: Iteration Plan for February 2020

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#2329]
This plan captures our work on the Remote development extensions in **February**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/90371). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote - Core
- [x] Monitor adoption of the new `extensionKind` [property](https://code.visualstudio.com/api/advanced-topics/remote-extensions#incorrect-execution-location) https://github.com/microsoft/vscode-internalbacklog/issues/932 by extensions @sandy081 @egamma

### Remote - SSH
- [x] Make password/passphrase UX more reliable on Windows https://github.com/microsoft/vscode-remote-release/issues/2338 @roblourens
- [x] Enable local server support by default in nightly https://github.com/microsoft/vscode-remote-release/issues/2339 @roblourens
- [x] Move remote Windows support out of preview https://github.com/microsoft/vscode-remote-release/issues/25 @roblourens
- [x] Explore remote macOS support https://github.com/microsoft/vscode-remote-release/issues/24 @roblourens

### Remote - Containers
- [x] Separate the Docker dependency from the Remote extension https://github.com/microsoft/vscode-remote-release/issues/2380 @chrmarti
- [x] Explore support to attach to Kubernetes https://github.com/microsoft/vscode-remote-release/issues/2381 @chrmarti
- [x] Add support for a `initializeCommand` to `devcontainer.json` https://github.com/microsoft/vscode-remote-release/issues/1045 @chrmarti
- [x] Make image building more flexible (buildArgs, target) https://github.com/microsoft/vscode-remote-release/issues/150 @chrmarti

### Remote - WSL
- [x] Using Docker in WSL2 blog post @fiveisprime

-----
### Deferred Items
- Explore using the git installed on Windows https://github.com/microsoft/vscode-remote-release/issues/1844 @aeschli
- Polish Remote Explorer Header https://github.com/microsoft/vscode/issues/86037 @alexr00 @misolori
- Open repository in Container, offer to create a `devContainer.json` when it doesn't exist already https://github.com/microsoft/vscode-remote-release/issues/1570 @egamma
