### ISSUE TITLE
Remote: Iteration Plan for April 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#2752]
This plan captures our work on the Remote development extensions in **April**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/95168). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote - Core
- [ ] :runner: Can't drag files from a remote vscode window to a local window https://github.com/microsoft/vscode-remote-release/issues/1149 @isidorn

### Remote - SSH
- [ ] :muscle: Provide an easy way to access a SSH devbox through the web UI @roblourens

### Remote - Containers
- [ ] :runner: Finalize Dev Containers in WSL2 support (improve path mapping, discover devcontainer config files) https://github.com/microsoft/vscode-remote-release/issues/2779 @chrmarti
- [x] Improve the dev container configuration experience https://github.com/microsoft/vscode-remote-release/issues/2757 @egamma @chrmarti
- [x] :runner: `devcontainer.json` add more variables like `${remoteWorkspaceFolder}` https://github.com/microsoft/vscode-remote-release/issues/2473 @chrmarti
- [x] :runner: Explore support for [Podman](https://podman.io/) https://github.com/microsoft/vscode-remote-release/issues/116 @chrmarti
- [ ] :runner: Explore speeding up container creation by caching extensions locally https://github.com/microsoft/vscode-remote-release/issues/2227 @sandy081
- [x] Adopt the latest `devContainer.json` improvements in the `vscode-remote-try-*` samples, e.g., `forwardPorts`. @Chuxel

### Remote - WSL
- [ ] Explore support for 'Save as Admin' https://github.com/microsoft/vscode-remote-release/issues/1688 @aeschli
- [ ] Engineering - provide an integration test @aeschli

-----
### Deferred Items
- Polish Remote Explorer Header https://github.com/microsoft/vscode/issues/86037 @alexr00 @misolori

**Comment by BCNelson** [comment]
Is there a reason that #1688 is only under WSL? I would hope that it would be supported under all remotes.

**Comment by aeschli** [comment]
@BCNelson I will prototype it for WSL first, but one it will then available for all remotes.

**Comment by PavelSosin-320** [comment]
I'm running Docker Desktop CE 2.3.0.0 edge on the top of Windows Pro dev pre-release of 2004 GA April 2000!. MS Dev containers running from Terminal window ignores my Docker context  - see attachment 
[dockerInfo.txt](https://github.com/microsoft/vscode-remote-release/files/4543569/dockerInfo.txt)
In other words, nothing ensures the correct execution of Microsoft development containers on my machine regardless of Microsoft's approval. This Docker stack will be most available ( no need in Hyper-V and DockerNAT ) and most performed (indeed!) very soon.
Please, pay attention to critical options like available networking options, init image, logging drivers, Swarm/Kubernetes orchestration mode. See attachment for the default, non-Kubernetes Docker infra configuration on my laptop.
[DockerSwarm.txt](https://github.com/microsoft/vscode-remote-release/files/4543635/DockerSwarm.txt)

I don't believe that the ordinal developer is able to provide the correct values of **docker run** . The correct VSCode Docker plugin task has to be provided ASAP to avoid the user's inconvenience.
