### ISSUE TITLE
Remote: Iteration Plan for May 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#2973]
This plan captures our work on the Remote development extensions in **May**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/97432). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote - Core
- [x] Investigate how resolvers can access tokens provided by Authtentication Providers https://github.com/microsoft/vscode-internalbacklog/issues/1116 @rmacfarlane @alexdima
- [x] Polish Remote Explorer Header https://github.com/microsoft/vscode/issues/86037 @alexr00 @misolori
- [x] Support to install a local extension into its preferrable location  https://github.com/microsoft/vscode/issues/83675 @sandy081
- [ ] :runner: Support to drag a file from a remote vscode window to a local windowÂ https://github.com/microsoft/vscode/issues/93599 @isidorn

### Remote - SSH
- None.

### Remote - Containers
- [x] Gracefully handle missing `image/dockerfile/dockerComoposeFile` https://github.com/microsoft/vscode-remote-release/issues/2937 @chrmarti
- [ ] :runner: Provide `postStartCommand`, `postAttachCommand`; explore `preDeleteCommand` https://github.com/microsoft/vscode-remote-release/issues/2772 @chrmarti
- [x] Explore speeding up container creation by caching extensions locally https://github.com/microsoft/vscode-remote-release/issues/2227 @chrmarti
- [x] Investigate support for signing commits when running in a dev container https://github.com/microsoft/vscode-remote-release/issues/72 @chrmarti
- [x] Enable `Dockerfile`/`devcontainer.json` iteration from repository containers, support to inspect a volume https://github.com/microsoft/vscode-remote-release/issues/2726 @egamma
- [ ] :runner: Investigate into a `devContainer.json` for the VS Code project for running in a Codespace  https://github.com/microsoft/vscode-dev-containers/issues/339 @Chuxel

### Remote - WSL
- [x] Remote-WSL user study (05/26) @fiveisprime

-----
### Deferred Items from previous iteration(s)
- :muscle: Provide an easy way to access a SSH devbox through Codespaces @roblourens
