### ISSUE TITLE
Remote: Iteration Plan for June 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#3175]
This plan captures our work on the Remote development extensions in **June**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/100100). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |
| :black_large_square:| a large work item, larger than one iteration      | 

### Remote - Core
- [x] Remote Explorer Help & Feedback: Allow to contribute commands in addition to URIs https://github.com/microsoft/vscode/issues/99661 @alexr00
- [ ] :runner: Investigate into automatic port forwarding based on output https://github.com/microsoft/vscode-remote-release/issues/3235 @alexr00

### Remote - SSH
- [x] Explore using sockets on the server side and forward those to the client https://github.com/microsoft/vscode-remote-release/issues/3234 @roblourens

### Remote - Containers
- [x] Adopt `onStartupFinished` event to enable reopen notifications for repository container configurations in [vscode-dev-containers](https://github.com/microsoft/vscode-dev-containers/tree/master/repository-containers)  https://github.com/microsoft/vscode-remote-release/issues/3196 @chrmarti
- [x] Investigate into a `devContainer.json` for the VS Code project for running in a Codespace  https://github.com/microsoft/vscode-dev-containers/issues/339 @Chuxel
- [x] Allow disabling of the "reopen" in dev container notification on a per-folder basis https://github.com/microsoft/vscode-remote-release/issues/3197 @chrmarti
- [x] Explore attaching to a container with a user defined name https://github.com/microsoft/vscode-remote-release/issues/3198 @chrmarti
- [x] Provide guidance to open a repository in a volume on macOS and Windows when the folder has a `.git` folder https://github.com/microsoft/vscode-remote-release/issues/3199 @chrmarti

### Remote - WSL
- None.

### Engineering
- [x] Enable auto-classification bot https://github.com/microsoft/vscode-remote-release/issues/3186 @jacksonkearl
- [x] Enable command bot https://github.com/microsoft/vscode-remote-release/issues/3187 @jacksonkearl

-----
### Deferred Items
- Support to drag a file from a remote vscode window to a local window https://github.com/microsoft/vscode/issues/93599 @isidorn

**Comment by bhack** [comment]
Any step in this iteration on the Kubernetes integration?

**Comment by chrmarti** [comment]
(Continuing the conversation with @bhack here: https://github.com/microsoft/vscode-remote-release/issues/12#issuecomment-644577515.)

**Comment by Stanzilla** [comment]
One regression that might be worth addressing: https://github.com/microsoft/vscode-remote-release/issues/3190

**Comment by CrazyOptimist** [comment]
Thanks a ton!!
This plugin is really great.
I can't say anything but THANK YOU for your hard work guys.
