### ISSUE TITLE
Remote: Iteration Plan for July 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#3347]
This plan captures our work on the Remote development extensions in **July**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/102174). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout. This is the start of the vacation season (July-August) and although not a lot of traveling is happening, our team still takes time off.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |
| :black_large_square:| a large work item, larger than one iteration      | 

### Remote - Core
- [ ] :runner: Investigate into automatic port forwarding based on output https://github.com/microsoft/vscode-remote-release/issues/3235 @alexr00

### Remote - SSH
- [x] Bring back flock for Linux servers https://github.com/microsoft/vscode-remote-release/issues/2518 @roblourens
- [x] Work with the Python extension on https://github.com/microsoft/vscode-remote-release/issues/1760 @roblourens

### Remote - Containers
- [x] Adopt the finalized AuthProvider (consumption) API https://github.com/microsoft/vscode-remote-release/issues/3342 @egamma

### Remote - WSL
- [x] Update `README.md` https://github.com/microsoft/vscode-remote-release/issues/3360 @bamurtaugh

-----
### Deferred Items
- None.

**Comment by fkx2016** [comment]
I'm working with VSC remotely with Nvidia Jetson Development kits (Xavier AGX, NX, Nano, TX2) running ubuntu 18.04 via SSH.
Things are working well for the most part.
Is this the thread to watch?

**Comment by ntziolis** [comment]
@kieferrm Are there any plans to open source these extension or at least allow a limited number of community members to contribute? https://github.com/microsoft/vscode-remote-release/issues/3405
