### ISSUE TITLE
Remote: Iteration Plan for August 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#3523]
This plan captures our work on the Remote development extensions in **August**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/104735). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout. Our vacation season continuous and although not a lot of traveling is happening, our team still takes time off.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |
| :black_large_square:| a large work item, larger than one iteration      | 

### Remote - Core
- [x] Automatic port forwarding based on terminal output https://github.com/microsoft/vscode-remote-release/issues/3235 @alexr00
- [x] Adopt Welcome support in the Remote Explorer contributions https://github.com/microsoft/vscode-remote-release/issues/3504 @alexr00

### Remote - SSH
- [x] Explore/fix reconnect issues https://github.com/microsoft/vscode-remote-release/issues/3533 @roblourens

### Remote - Containers
- [x] Investigate into supporting Docker compose when cloning a repository in a container volume https://github.com/microsoft/vscode-remote-release/issues/3404 @chrmarti
- [x] Explore how to simplify process of customizing `Dockerfile`s https://github.com/microsoft/vscode-remote-release/issues/3590 @chrisdias @Chuxel @bamurtaugh @chrmarti
- [ ] :runner: Clone Repository into Container Volume investigate adding support for `workspaceMount` `workspaceFolder` configuration options https://github.com/microsoft/vscode-remote-release/issues/3034 @egamma
- [x] Integrate the GitHub repository picker when cloning a repository in a container volume https://github.com/microsoft/vscode-remote-release/issues/3537 @egamma

#### VS Code Devcontainer Configurations
- [x] Onboard additional definitions to image build - Java, .NET, Go, Rust, Ruby @Chuxel
- [x] Switch to using "library-scripts" approach for common scripts @Chuxel
- [x] Add optional node install for all definitions with languages commonly used for web development @Chuxel

### Remote - WSL
- None.

-----
### Deferred Items
- None.
