### ISSUE TITLE
Remote: Iteration Plan for September 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#3669]
This plan captures our work on the Remote development extensions in **September**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/xxxx). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |
| :black_large_square:| a large work item, larger than one iteration      |

### Remote - Core
- [x] Notify user when an automatically detected port is forwarded https://github.com/microsoft/vscode-remote-release/issues/3662 @alexr00

### Remote - SSH
- [ ] :runner: Investigate reliability of Remote-SSH connections https://github.com/microsoft/vscode-remote-release/issues/3670 @bamurtaugh @roblourens

### Remote - Containers
- [x] Improve creation log access and rendering https://github.com/microsoft/vscode-remote-release/issues/3666 @chrmarti
- [ ] :runner: Support to rebuild and open the `devcontainer.json` from the Container details section https://github.com/microsoft/vscode-remote-release/issues/3667 @chrmarti
- [x] Improve the dev container innerloop when cloning a repository into a container volume https://github.com/microsoft/vscode-remote-release/issues/3664 @egamma

#### VS Code Devcontainer Configurations
- [x] Onboard additional definitions to image build https://github.com/microsoft/vscode-dev-containers/issues/154 @Chuxel
- [x] Build out "library-scripts" for dev container configurations https://github.com/microsoft/vscode-dev-containers/issues/560 @Chuxel

### Remote - WSL
- [x] Investigate how to guide users to the first WSL session after they have installed the WSL extension https://github.com/microsoft/vscode-remote-release/issues/3671 @aeschli @bamurtaugh
- [x] Investigate inheriting the environment from the process where `code .` is executed https://github.com/microsoft/vscode-remote-release/issues/1700 @aeschli
- [x] Document how to get more detailed error logs and core dump files https://github.com/microsoft/vscode-remote-release/issues/3679 @aeschli

-----
### Deferred Items
- Investigate supporting `.code-workspace file` attribute in `devcontainer.json` https://github.com/microsoft/vscode-remote-release/issues/3665 @chrmarti
- :muscle: Warn user when deleting a container volume that has uncommitted changes @chrmarti
