### ISSUE TITLE
Remote: Iteration Plan for November 2020

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#4017]
This plan captures our work on the Remote development extensions in **November**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/110690). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

We've spent the first two weeks of this iteration finishing our annual housekeeping. If you are interested in why we have issue house keeping iterations and in our general philosophy around issue management, then we have this [write-up](https://github.com/microsoft/vscode/wiki/Issue-Grooming) for you.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Housekeeping
- [x] Issue/PR Grooming - review, categorization, assignment. We work with on tracking item across all our repositories: https://github.com/microsoft/vscode/issues/108472 **team**

### Remote Core
- [x] Support that an extension running inside a remote context can open a URL in a locally running browser https://github.com/microsoft/vscode-remote-release/issues/3992 @aeschli
- [x] Detect open/closed ports dynamically independent of the output to the console https://github.com/microsoft/vscode-remote-release/issues/3996 @alexr00
- [ ] :runner: Ports view polish https://github.com/microsoft/vscode-remote-release/issues/4021 @alexr00
- [x] Enable binding privileged ports https://github.com/microsoft/vscode-remote-release/issues/3922 @alexr00
- [ ] :muscle: Support additional ports attributes (name, ignored) https://github.com/microsoft/vscode-remote-release/issues/4046 @alexr00

### Remote-SSH
- [x] Capture the different phases of the Remote-SSH startup for performance analysis https://github.com/microsoft/vscode-remote-release/issues/4030 @roblourens
- [x] Support parameters to `opensshremotes.openEmptyWindow` https://github.com/microsoft/vscode-remote-release/issues/3552 @roblourens

### Remote-WSL
- [ ] :muscle: :runner: Explore experience when Remote WSL extension is installed out of the box on Windows, see also https://github.com/microsoft/vscode/issues/106759 @aeschli

### Remote Samples
- [ ] :muscle: :runner: Switch to using dynamic port forwarding in the samples https://github.com/microsoft/vscode-remote-release/issues/3933 @egamma @Chuxel
