### ISSUE TITLE
Remote Iteration Plan for January 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#4184]
This plan captures our work in late **December** and **January**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/112419). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote Core
- [x] Ports view polish https://github.com/microsoft/vscode-remote-release/issues/4021 @alexr00
- [x] Support additional ports attributes (name, ignored) https://github.com/microsoft/vscode-remote-release/issues/4046 @alexr00
- [x] Improved update of machine scoped settings, e.g. the python path https://github.com/microsoft/vscode-remote-release/issues/1801 @sandy081
- [x] Add support for the "--install-extension" argument to the Remote CLI https://github.com/microsoft/vscode-remote-release/issues/2589 @aeschli

### Remote-SSH
- None

### Remote-Container
- [x] Support SSH connection with password entry https://github.com/microsoft/vscode-remote-release/issues/4154 @chrmarti

### Remote-WSL
- [x] Explore a 'WSL stub' extension that guides users to install the WSL extension https://github.com/microsoft/vscode-remote-release/issues/4255 @aeschli @bamurtaugh

### Remote Samples
- [x] Switch to using dynamic port forwarding in the samples https://github.com/microsoft/vscode-remote-release/issues/3933 @bamurtaugh @Chuxel

**Comment by AlbertoPdRF** [comment]
Hey! 👋

First of all, sorry if this is not the right place to ask, but I figured it was better to leave just one comment here instead of various across issues. Are there any plans to fix #267 and #589 soon? I can seem to get things working with the workarounds mentioned on the issues (at least on Windows, I haven't been able to try on Linux yet), but it would be nice to have a definitive fix for this.

Thanks in advance! 🙂
