### ISSUE TITLE
Remote Iteration Plan for February 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#4430]
This plan captures our work in **February**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/116000). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote Core
- [x] Enable the Simple Browser for previewing end points exposed by forwarded ports https://github.com/microsoft/vscode-remote-release/issues/4436 @alexr00 @mjbvz
- [x] Ports view polish https://github.com/microsoft/vscode/issues/116058 @alexr00
- [ ] :hand: Notarize the VS Code Server for macOS https://github.com/microsoft/vscode/tree/robo/reh_server_notarize @deepak1556

### Remote-SSH
- [ ] :muscle: Explore how the resolver can deal more flexibly with long install scripts https://github.com/microsoft/vscode-remote-release/issues/4487 @roblourens
- [x] :muscle: Explore X11 forwarding https://github.com/microsoft/vscode-remote-release/issues/589 @roblourens 

### Remote-Container
- [x] Support portAttributes as a top level attribute in `devContainer.json` https://github.com/microsoft/vscode-remote-release/issues/4432 @alexr00 @chrmarti
- [x] Support to update the port attributes in `devcontainer.json` when a user assigns a label to a port https://github.com/microsoft/vscode-remote-release/issues/4433 @alexr00
- [x] Move the `postCreateCommand` execution to the background https://github.com/microsoft/vscode-remote-release/issues/4446 @chrmarti
- [x] Add category metadata to the existing `vscode-dev-containers` https://github.com/microsoft/vscode-dev-containers/pull/740 @chuxel
- [x] Adopt the category metadata in the 'Add dev container' command (only show `Core` containers in the first level of the quick pick) https://github.com/microsoft/vscode-remote-release/issues/4447 @egamma @chrmarti

### Remote-WSL
- [x] Suggest storing source code in WSL2 when `/mnt` folder is opened https://github.com/microsoft/vscode-remote-release/issues/4454 @aeschli
- [x] Fallback to polling when run on a `/mnt` network drive https://github.com/microsoft/vscode-remote-release/issues/4455 @aeschli
