### ISSUE TITLE
Remote Iteration Plan for March 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#4609]
This plan captures our work in **March**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/118334). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote Core
- [ ] :runner: Do not auto forward debug port by inform tunneling service about debug ports https://github.com/microsoft/vscode/issues/115616 @alexr00 @connor4312
- [x] Improve auto port detection for processes running as root https://github.com/microsoft/vscode-remote-release/issues/4654

### Remote-SSH
- [x] Support latest version of Windows SSH https://github.com/microsoft/vscode-remote-release/issues/2475 @roblourens
- [ ] :muscle: Provide an option for a pre-configured range of ports that the server can use https://github.com/microsoft/vscode-remote-release/issues/1386 @roblourens
- [ ] :muscle: Explore how the resolver can deal more flexibly with long install scripts https://github.com/microsoft/vscode-remote-release/issues/4487 @roblourens

### Remote-Container
- [x] Investigate Trusted Workspaces support https://github.com/microsoft/vscode-remote-release/issues/4635 @chrmarti
- [x] Support `initializeCommand` scripts that works across Windows and Codespaces https://github.com/microsoft/vscode-remote-release/issues/4568 @chrmarti
- [x] Additional `portsAttributes` https://github.com/microsoft/vscode-remote-release/issues/4623 @alexr00
- [x] Ports view: Set Label command polish https://github.com/microsoft/vscode-remote-release/issues/4624 @alexr00

### Remote Samples
- [x] Update dev container samples to use new port attributes https://github.com/microsoft/vscode-remote-release/issues/4616 @bamurtaugh

----
### Deferred
- None.
