### ISSUE TITLE
Remote Iteration Plan for April 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#4822]
This plan captures our work in **April**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/120585). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote Core
- [x] Do not auto forward debug port by inform tunneling service about debug ports https://github.com/microsoft/vscode/issues/115616 @alexr00 @connor4312
- [x] Ports view polish https://github.com/microsoft/vscode-remote-release/issues/4826 @alexr00
- [x] Investigate why custom views don't load correctly in remote scenarios https://github.com/microsoft/vscode/issues/102449 @mjbvz
- [x] Investigate in improved rendering of the Remote Command Palette https://github.com/microsoft/vscode-remote-release/issues/4831 @aeschli

### Remote-SSH
- [ ] :muscle: Provide an option for a pre-configured range of ports that the server can use https://github.com/microsoft/vscode-remote-release/issues/1386 @roblourens
- [ ] :muscle: Explore how the resolver can deal more flexibly with long install scripts https://github.com/microsoft/vscode-remote-release/issues/4487 @roblourens

### Remote-Container
- [x] Simplify the rendering of containers in the Remote Explorer https://github.com/microsoft/vscode-remote-release/issues/4829 @alexr00
- [x] Investigate into installing docker when it isn't installed microsoft/vscode-remote-release/issues/4906 @chrmarti
- [x] Add support for viewing and managing volumes in the Remote Explorer https://github.com/microsoft/vscode-remote-release/issues/4830 @egamma
- [x] Simplify 'Clone Repository in Container Volume' command @egamma

### Remote Samples
- [x] Review whether the recent port attributes improvements should be demonstrated in the samples https://github.com/microsoft/vscode-remote-release/issues/4838 @bamurtaugh

----
### Deferred
- None.
