### ISSUE TITLE
Remote Iteration Plan for May 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#5022]
This plan captures our work in **May**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/123368). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote Core
- Port forwarding
  - [x] Warn on port collisions when forwarding ports https://github.com/microsoft/vscode-remote-release/issues/4958 @alexr00
  - [x] Add option to disable auto port forwarding but still get the process association for a port https://github.com/microsoft/vscode-remote-release/issues/4923 @alexr00
  - [x] Provide command to remove all forwarded ports https://github.com/microsoft/vscode/issues/121780 @alexr00
  - [x] Support to define the protocol to be used when connecting to a forwarded port https://github.com/microsoft/vscode/issues/123750 @alexr00

### Remote-SSH
- [ ] :muscle: Provide an option for a pre-configured range of ports that the server can use https://github.com/microsoft/vscode-remote-release/issues/1386 @roblourens

### Remote-Container
- [x] Trusted Folder/Workspaces support for remote containers https://github.com/microsoft/vscode-remote-release/issues/5067 @chrmarti @lszomoru @alexdima
- [x] Merge `PATH` environment variable when probing the user environment https://github.com/microsoft/vscode-remote-release/issues/5032 @chrmarti
- [x] Align the use of Volumes for 'Try a Development Container Sample with the 'Clone a Repository in Container Volume' https://github.com/microsoft/vscode-remote-release/issues/4955 @egamma
- [ ] Engineering: explore publishing the extension through a CI/CD flow https://github.com/microsoft/vscode-remote-release/issues/5069 @chrmarti

### Remote Samples
- None.

----
### Deferred
- None.
