### ISSUE TITLE
Remote Iteration Plan for June 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#5183]
This plan captures our work in **June**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/126181). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote Core
- [x] Port forwarding add protocol configuration support to the tunnel API @alexr00

### Remote-SSH
- [x] Investigate recent SSH connection issues [#5116](https://github.com/microsoft/vscode-remote-release/issues/5116) @roblourens
- [ ] :muscle: Provide an option for a pre-configured range of ports that the server can use [#1386](https://github.com/microsoft/vscode-remote-release/issues/1386) @roblourens

### Remote-Container
- [x] Explore to support "host requirements" in `devContainer.json` [#5189](https://github.com/microsoft/vscode-remote-release/issues/5189) @chrmarti
- [x] Engineering: explore publishing the extension through a CI/CD flow [#5069](https://github.com/microsoft/vscode-remote-release/issues/5069) @chrmarti

### Remote Samples
- None.

----
### Deferred
- None.

**Comment by gyzerok** [comment]
Can't wait for this stretch goal to finally hit "merge"! I've been looking for this feature for almost a year now. So excited you are finally doing it :)
