### ISSUE TITLE
Remote : Iteration Plan for July 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#5315]
This plan captures our work in **July**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/128444). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote Core
- None.

### Remote-SSH
- None.

### Remote-Container
- [x] Add a devcontainer CLI - provide command to open a folder in Remote-Containers [vscode-remote-release#5302](https://github.com/microsoft/vscode-remote-release/issues/5302) @stuartleeks
- [x] Devcontainer CLI - provide command to build the dev container image [vscode-remote-release#5349](https://github.com/microsoft/vscode-remote-release/issues/5349) @stuartleeks
- [x] Allow rebuild a container without the cache [vscode-remote-release#2200](https://github.com/microsoft/vscode-remote-release/issues/2200) @chrmarti

### Remote Samples
- None.

----
### Deferred
- [ ] Provide an option for a pre-configured range of ports that the server can use [vscode-remote-release#1386](https://github.com/microsoft/vscode-remote-release/issues/1386) @roblourens
