### ISSUE TITLE
Remote: Iteration Plan for August 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#5428]
This plan captures our work in **August**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/130368). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote Core
- [x] Enable port forwarding to another host [vscode#131399](https://github.com/microsoft/vscode/issues/131399) @alexdima

### Remote-SSH
- [ ] :runner: Investigate reports on commit mismatch on client-server handshake [vscode-remote-release#5303](https://github.com/microsoft/vscode-remote-release/issues/5303) @roblourens

### Remote-Container
-  [ ] :runner: Explore simplifying dev container definition with a concept of 'container features' [vscode-remote-release#5442](https://github.com/microsoft/vscode-remote-release/issues/5442) @chrmarti @Chuxel
- Dev Container CLI
    - [ ] :runner: Mac OS: offer to add the CLI to the system path [vscode-remote-release#5443](https://github.com/microsoft/vscode-remote-release/issues/5443) @chrmarti, @stuartleeks
    - [ ] :runner: Support to run dev container image build in a CI build [vscode-remote-release#5415](https://github.com/microsoft/vscode-remote-release/issues/5415) @stuartleeks
    - [ ] :runner: Add `devcontainer run` command [vscode-remote-release#5416](https://github.com/microsoft/vscode-remote-release/issues/5416) @stuartleeks
    - [ ] :red_circle: Integrate the Dev Container CLI with the VS Code CLI, e.g. code --open-in-devcontainer .
    - [ ] :muscle: :red_circle: Add support for repository containers (add `clone-in-volume` as a command,  Add `--volume` option to open folder in a volume
- [ ] Adopt port forwarding to another host [vscode-remote-release#3450](https://github.com/microsoft/vscode-remote-release/issues/3450) @alexr00

### Remote-WSL
- None.

### Remote Samples
- None.

----
### Deferred
- [ ] Provide an option for a pre-configured range of ports that the server can use [vscode-remote-release#1386](https://github.com/microsoft/vscode-remote-release/issues/1386) @roblourens

**Comment by rhlobo** [comment]
> * Integrate the Dev Container CLI with the VS Code CLI, e.g. code --open-in-devcontainer .

missing issue reference: #2900
