### ISSUE TITLE
Remote: Iteration Plan for September 2021

### ISSUE THREAD

**Issue by egamma** [microsoft/vscode-remote-release#5552]
This plan captures our work in **September**. We follow the same iteration cycle as [VS Code](). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote-Container
- [ ] :runner: Simplify dev container definition with reusable 'dev container features' [vscode-remote-release#5442](https://github.com/microsoft/vscode-remote-release/issues/5442) @chrmarti @Chuxel
- [x] Adopt port forwarding to another host [vscode-remote-release#3450](https://github.com/microsoft/vscode-remote-release/issues/3450) [vscode-remote-containers#150](https://github.com/microsoft/vscode-remote-containers/pull/150) @alexr00 @chrmarti
- [x] Support to attach to a Podman container running under WSL [vscode-remote-release#5550](https://github.com/microsoft/vscode-remote-release/issues/5550) @chrmarti
- [x] Create an arm64 build of the VS Code server for Alpine [vscode-remote-release#5187](https://github.com/microsoft/vscode-remote-release/issues/5187) @TylerLeonhardt

### Remote-WSL
- [x] Investigate whether platform specific extensions can be leveraged for WSL and constrain the installation to Windows [vscode#23251](https://github.com/microsoft/vscode/issues/23251) @aeschli @sandy081

----
### Deferred
- [ ] Provide an option for a pre-configured range of ports that the server can use [vscode-remote-release#1386](https://github.com/microsoft/vscode-remote-release/issues/1386) @roblourens

**Comment by PederBennedsen** [comment]
Could you please prioritize #4600 etc. concerning X11 forwarding?
It is such a drawback that we can only debug text UI...
