### ISSUE TITLE
Remote: Iteration Plan for November 2021

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#5828]
This plan captures our work in **November**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/136630). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| 🏃‍♀️                   | work in progress                                  |
| ✋                   | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- [x] Improve connection stability between the VS Code client and Server [vscode#137863](https://github.com/microsoft/vscode/pull/137863) @alexdima

### Remote-SSH
- [x] Provide an option for a pre-configured range of ports that the server can use [vscode-remote-release#1386](https://github.com/microsoft/vscode-remote-release/issues/1386) @tanhakabir

### Remote-Container
- [x] Start to explore "Reopen Folder in Container" from SSH [vscode-remote-release#2994](https://github.com/microsoft/vscode-remote-release/issues/2994) @chrmarti
- [x] Review/add commands to be surfaced when connected from WSL [vscode-remote-release#5765](https://github.com/microsoft/vscode-remote-release/issues/5765) @chrmarti
- [x] 'Add development configuration files' support to navigate to the documentation for a feature/configuration [microsoft/vscode-remote-release#5899](https://github.com/microsoft/vscode-remote-release/issues/5899) @chrmarti
- [x] Use the pre-built alpine image for the recovery container [microsoft/vscode-remote-release#5897](https://github.com/microsoft/vscode-remote-release/issues/5897) @chrmarti
- [x] Engineering: generate 3rd party usages automatically [microsoft/vscode-remote-release#5898](https://github.com/microsoft/vscode-remote-release/issues/5898) @chrmarti @lszomoru

### Remote-WSL
- [x] Engineering: Explore communicating with WSL using stdin/stdout instead of TCP/IP to increase connection reliability [vscode-remote-release#5894](https://github.com/microsoft/vscode-remote-release/issues/5894) @aeschli

----
### Deferred
- None.
