### ISSUE TITLE
Integration of WSL and remote extensions does not work with WSL SSH client

### ISSUE THREAD

**Issue by alkatar21** [microsoft/vscode-remote-release#6061]
Currently there are some problems, some of which are already available as issues:
- One thing is that it is not possible to simply specify a WSL of your choice as SSH client in the Remote-SSH extension (#937), which requires the following [workaround](https://github.com/microsoft/vscode-remote-release/issues/937#issuecomment-980509520).
  - This also needs to be able to handle a login shell, for example to handle a [ssh-agent](https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent) for [Docker Contexts](https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host#_connect-using-docker-contexts).
  - The Remote-Containers extension should take this option into account, as you currently can't start a container with a local `devcontainer.json`, as the Remote-Containers extension tries to use a local SSH client instead of the one of the Remote-SSH extension. Which is either not available or should not be used.
  - The same problem exists with the new [release](https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_63.md#containers-version-0209x) for the open folder in container on SSH server feature.
- It is not possible to specify a WSL to use for commands in the Remote-Containers extension (#5774).
  - This results in anyone who does not have docker in their defaut WSL not being able to use the option.
    Since this option has side effects, as seen for example in (#6053) with the new [update](https://github.com/microsoft/vscode-docs/blob/main/remote-release-notes/v1_63.md#containers-version-0209x) (Open folder in container on SSH server), is a problem, as it also specifies which SSH client is used. However, this is again a problem with a non-uniform ssh client in the extensions.

This means that you cannot work in containers on remote servers if you do not want to or cannot use the Windows OpenSSH client.

A consistent use of a SSH client in these extensions, which can also be a WSL ssh and the possibility to choose a WSL distro for the remote containers extension, would probably solve all described problems.

Solutions:
- [ ] Remote-SSH Extension: Add support to discover WSL SSH (#937)
- [ ] Remote-Docker Extension: Add option to set an alternate distro for docker commands (#5774)
- [ ] Remote-Docker Extension: Use Remote-SSH extensions ssh option (`"remote.SSH.path"` `"remote.SSH.configFile"`) to select the right ssh-client and not use the system one or the default WSL one with the WSL option (`"remote.containers.executeInWSL": true`) (#6021, #6053).

- VSCode Version: 1.63.0
- Local OS Version: Windows11
- Remote OS Version:  Ubuntu 20.04.3 LTS
- Remote Extension/Connection Type: SSH/Docker/WSL
  - Remote - Containers v0.209.6
  - Remote - SSH v0.69.2021121415
  - Remote Docker Version: Docker version 20.10.11
  - Local Docker Version: Docker version 20.10.11, build dea9396

**Comment by alkatar21** [comment]
To give an update.
Thanks to https://github.com/microsoft/vscode-remote-release/issues/6021#issuecomment-1000723794 it is now possible at all to work in containers on an remote host with the initially mentiond [workaround](https://github.com/microsoft/vscode-remote-release/issues/937#issuecomment-980509520).
Together with this fix and #5774, it is now possible for me to at least use `"remote.containers.executeInWSL": true` and to Develop on a remote Docker host.

The following points remain:
- It is not possible to simply specify a WSL of your choice as SSH client in the Remote-SSH extension (#937), which currently requires the following [workaround](https://github.com/microsoft/vscode-remote-release/issues/937#issuecomment-980509520).
  - This maybe also needs to be able to handle a login shell, for example to handle a [ssh-agent](https://code.visualstudio.com/docs/remote/troubleshooting#_setting-up-the-ssh-agent) for [Docker Contexts](https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host#_connect-using-docker-contexts) (If this setting can be used for an `ssh-agent`?).
- It is still not possible to use the `ssh-agent` of a WSL distro to work with [docker contexts](https://code.visualstudio.com/remote/advancedcontainers/develop-remote-host#_connect-using-docker-contexts). I don't know if you need to be able to specify this separately, or if `"remote.SSH.path"` could also be used for this?

I am not quite sure how to proceed with this issue. I could note the first part in the noted issue and create a new issue for the second part, since I can not find an open one for this, or leave the current one open?

**Comment by roblourens** [comment]
Closing as dupe of https://github.com/microsoft/vscode-remote-release/issues/937
