### ISSUE TITLE
Remote: Iteration Plan for June 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#608]
This plan captures our work on the Remote development extensions in **June**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/75103). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

We'll focus stability, improving the first time user experience, and overall polishing.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### UX
- [x] Add `Close Connection` https://github.com/microsoft/vscode-remote-release/issues/501 @aeschli
- [x] :runner: Make it easier for first time users to understand that they are in a remote context https://github.com/microsoft/vscode-remote-release/issues/511 @isidorn

### Remote - Core
- [x] Fallback to stream extensions from the client to the server when marketplace access fails https://github.com/microsoft/vscode-remote-release/issues/231 @sandy081
- [x] :runner: **File: Save As** should support to save remote files on the local machine https://github.com/microsoft/vscode-remote-release/issues/712 @alexr00
- [x] Support DnD of local files and folders into the file explorer in a remote context https://github.com/microsoft/vscode-remote-release/issues/627 @isidorn
- [x] Since it is not possible to copy a folder from remote using DnD (Chrome limitation) there will be a separate command contributed on folders 'Download to Local...' @isidorn
- [x] :runner: Handle `127.0.0.1:port` just like `localhost:port` in WebViews https://github.com/microsoft/vscode-remote-release/issues/108 @mjbvz
- [x] Provide ARM32 server support https://github.com/Microsoft/vscode-remote-release/issues/13 @joaomoreno

### Remote - SSH
- [x] Improve handling of password authentication (reduced # of connections, prompt for password) https://github.com/microsoft/vscode-remote-release/issues/513 @roblourens
- [x] Improve how to handle disconnected/broken windows https://github.com/microsoft/vscode-remote-release/issues/641 @roblourens
- [ ] :runner: Take down VS Code Server processes when there are no clients https://github.com/microsoft/vscode-remote-release/issues/203 @roblourens
- [x] Improve find SSH binary on Window clients https://github.com/microsoft/vscode-remote-release/issues/448 @roblourens
- [x] :runner: Move connection history from explorer extension to SSH core extension https://github.com/microsoft/vscode-remote-release/issues/638 @kieferrm
- [x] Add command **Remote-SSH: Show Log** https://github.com/microsoft/vscode-remote-release/issues/639 @kieferrm
- [ ] :runner: Explore support for `SSH Agent` forwarding https://github.com/microsoft/vscode-remote-release/issues/16 @roblourens
- [ ] :muscle: Explore further improvements to password authentication https://github.com/microsoft/vscode-remote-release/issues/642 @roblourens
- [ ] :muscle: Explore connection sharing between windows that connect to the same host https://github.com/microsoft/vscode-remote-release/issues/96 @roblourens

### Remote - Containers
- [x] Improve logic in determining where to install agent (better `$HOME` detection) https://github.com/microsoft/vscode-remote-release/issues/22 @chrmarti
- [x] Pick up default shell from `/etc/passwd` if `$SHELL` not set and not overridden in VS Code settings https://github.com/microsoft/vscode-remote-release/issues/521 @chrmarti
- [x] Polish: Update name of **Remote-Containers: Add Container Configuration File** command https://github.com/microsoft/vscode-remote-release/issues/266 @chrmarti
- [x] Add command **Remote-Containers: Show Log** https://github.com/microsoft/vscode-remote-release/issues/673 @chrmarti
- [x] :runner: Improve test coverage for Remote-Containers https://github.com/microsoft/vscode-remote-release/issues/674 @chrmarti
- [x] :runner: Alpine Linux support https://github.com/microsoft/vscode-remote-release/issues/54 @chrmarti

### Remote - WSL
- [x] Support multiple Linux distros https://github.com/microsoft/vscode-remote-release/issues/118 @aeschli
- [x] Reenable file watcher logging to track down https://github.com/microsoft/vscode-remote-release/issues/314 SCM doesn't show changed files @aeschli
- [x] Download VS Code server from VS Code to address https://github.com/microsoft/vscode-remote-release/issues/79 @aeschli
- [x] Investigate into work around for WSL 1 limitation that you cannot rename non-empty folders https://github.com/microsoft/vscode-remote-release/issues/208 @aeschli

### Extension Contributions
- [x] Help to migrate the partner and most important extensions to use `machine`-scoped settings @sandy081
- [x] Investigate Chrome debug extension support for Remote https://github.com/microsoft/vscode-chrome-debug/issues/832 @roblourens

### Engineering
- Support/publish Nightly/insiders version
   - [x] Remote-SSH @roblourens
   - [ ] :runner: Remote-Containers https://github.com/microsoft/vscode-remote-release/issues/675 @chrmarti
   - [ ] :red_circle: Remote-WSL @aeschli

-------

### Deferred Items
- Align output channels/terminals across the remote extensions

**Comment by positivedefinite** [comment]
Dear dev team of vscode-remote,

This extension changed my life. I build NLP solutions on AWS. My lifestyle is typical for a digital nomad, I work from at least 3 different locations every week and I move a lot with public transport. My device of choice has been MS Surface Pro 3 with i7. It makes all the difference in the world that I can now run my code directly on EC2 and that VSCode takes 700 MB of RAM and not 2.5GB. For the early stage extension that vscode-remote is, I have had an absolutely fantastic experience with it in the past 3 weeks.

Keep up the good work!
