### ISSUE TITLE
Remote: Iteration Plan for January 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#6089]
This plan captures our work in **January**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/139607). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| 🏃‍♀️                   | work in progress                                  |
| ✋                   | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- None.

### Remote-SSH
- [x] Investigate support for `RemoteCommand` [vscode-remote-release#4474](https://github.com/microsoft/vscode-remote-release/issues/4474) @tanhakabir
- [x] Add command to kill the vscode server on currently connected host [vscode-remote-release#3170](https://github.com/microsoft/vscode-remote-release/issues/3170) @tanhakabir
- [x] Properly clean up old server data in remotes [vscode-remote-release#5955](https://github.com/microsoft/vscode-remote-release/issues/5955) @tanhakabir

### Remote-Container
- [x] Investigate into code sharing opportunities with remote SSH @chrmarti @roblourens @tanhakabir [vscode-remote-release#6137](https://github.com/microsoft/vscode-remote-release/issues/6137)
- [x] Add JSON schema for work-in-progress `features.json` [vscode-remote-release#5980](https://github.com/microsoft/vscode-remote-release/issues/5980) @chrmarti @joshspicer @Chuxel 
- [x] 'Add development configuration files' support to navigate to the documentation for a configuration [microsoft/vscode-remote-release#5899](https://github.com/microsoft/vscode-remote-release/issues/5899) @chrmarti
- [x] Investigate firing feature entrypoint in the case of docker compose [vscode-remote-release#5983](https://github.com/microsoft/vscode-remote-release/issues/5983) @chrmarti
- [x] Engineering - Adopt the preview extension support [vscode-remote-release#6169](https://github.com/microsoft/vscode-remote-release/issues/6169) @chrmarti 

### Remote-WSL
- None.

----
### Deferred
- None.
