### ISSUE TITLE
Remote: Iteration Plan for March 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#6421]
This plan captures our work in **March**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/144519). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| 🏃‍♀️                   | work in progress                                  |
| ✋                   | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- [x] Ship darwin arm64 server support [#vscode-remote#4069](https://github.com/Microsoft/vscode-remote-release/issues/4069) @alexdima
- [x] Report remote extension host crashes more gracefully and auto recover if possible [vscode#143645](https://github.com/microsoft/vscode/issues/143645) @alexdima

### Remote-SSH
- [ ] :runner: Adopt darwin arm64 server support for connecting to Apple M1 [#vscode-remote#4069](https://github.com/Microsoft/vscode-remote-release/issues/4069) @tanhakabir

### Remote-Container
- [ ] :runner: Move settings and extensions properties to vscode namespace [dev-container-spec#1](https://github.com/microsoft/dev-container-spec/issues/1) @chrmarti
- [x] Support to install pre-release extensions into a dev container and expose this in the `devcontainer.json` [vscode#143540](https://github.com/microsoft/vscode/issues/143540) @sandy081 @chrmarti

### Remote-WSL
- None.

----
### Deferred
- [ ] Honor user-defined values for `SSH_ASKPASS` [vscode-remote-release#4747](https://github.com/microsoft/vscode-remote-release/issues/4747) @tanhakabir
- [ ] :red_circle: Investigate terminal errors when opening a remote folder in a local window @tanhakabir
