### ISSUE TITLE
Remote: Iteration Plan for April 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#6554]
This plan captures our work in **April**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/146672). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| 🏃‍♀️                   | work in progress                                  |
| ✋                   | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- [x] Support for CentOS7 on ARM [#vscode-remote#2998](https://github.com/Microsoft/vscode-remote-release/issues/2998) @deepak1556

### Remote-SSH
- None.

### Remote-Container
- [x] Move settings and extensions properties to vscode namespace [dev-container-spec#1](https://github.com/microsoft/dev-container-spec/issues/1) @chrmarti

### Remote-WSL
- None.

----
### Deferred
- [ ] Honor user-defined values for `SSH_ASKPASS` [vscode-remote-release#4747](https://github.com/microsoft/vscode-remote-release/issues/4747) @tanhakabir
- [ ] :red_circle: Investigate terminal errors when opening a remote folder in a local window @tanhakabir
