### ISSUE TITLE
Remote: Iteration Plan for May 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#6699]
This plan captures our work in **May**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/149008). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                 | Description                                       |
| -------------------- | ------------------------------------------------- |
| 🏃‍♀️                   | work in progress                                  |
| ✋                   | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- [x] Allow open tunnel API to specify an `undefined` tunnel privacy setting @alexr00
- [ ] :runner: Avoid that the desktop version is opened when running 'code' in a remote terminal [vscode-remote-release#6625](https://github.com/microsoft/vscode-remote-release/issues/6625) @aeschli

### Remote-SSH
- [x] Localize Remote-SSH [vscode-remote-release#6702](https://github.com/microsoft/vscode-remote-release/issues/6702) @tanhakabir

### Remote-Container
- [x] Update definitions in vscode-dev-containers to use the new `customizations` property [devcontainers/spec#1](https://github.com/devcontainers/spec/issues/1#issuecomment-1036612267) ([PR](https://github.com/microsoft/vscode-dev-containers/pull/1447)) @bamurtaugh

### Dev Container Specification / CLI
- [ ] :runner: Prepare Dev Container Spec for public release [devcontainers/spec#30](https://github.com/devcontainers/spec/issues/30) @bamurtaugh @chrmarti
     - [x] Blog Post for DevContainer CLI launch [vscode-docs/pull#5347](https://github.com/microsoft/vscode-docs/pull/5347) @bamurtaugh @chrmarti
- [x] Add a try-out example to DevContainer CLI `README.md` [devcontainers/cli#4](https://github.com/devcontainers/cli/pull/4) @chrmarti
- [x] Add deprecation notice to [`@vscode/dev-container-cli`](https://www.npmjs.com/package/@vscode/dev-container-cli) [vscode-remote-release#6737](https://github.com/microsoft/vscode-remote-release/issues/6737) @chrmarti
- [ ] :muscle: Add `code` CLI argument to open folder in container using remote containers extension [vscode-remote-release#6771](https://github.com/microsoft/vscode-remote-release/issues/6771) @chrmarti
- [ ] :runner: Update GitHub Actions & Azure DevOps Extension to use new DevContainer CLI once it is public [devcontainers#39](https://github.com/devcontainers/cli/issues/39) @stuartleeks @chrmarti

### Remote-WSL
- [x] Localize Remote-WSL [vscode-remote-release#6695](https://github.com/microsoft/vscode-remote-release/issues/6695) @aeschli

----
### Deferred
- None.

**Comment by bhack** [comment]
Please consider https://github.com/microsoft/vscode-remote-release/issues/6746 if there is enough time.
