### ISSUE TITLE
Remote: Iteration Plan for June 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#6818]
This plan captures our work in **June**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/151843). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- None.

### Remote-SSH
- None.

### Remote-Container
- None.

### Dev Container Specification / CLI
- [x] Prepare Dev Container Spec for release [devcontainers/spec#30](https://github.com/devcontainers/spec/issues/30) @bamurtaugh @chrmarti
- [ ] :muscle: Replace old devcontainer CLI with new CLI in path [vscode-remote-release#6859](https://github.com/microsoft/vscode-remote-release/issues/6859) @chrmarti
- [x] Support for multi-platform builds [devcontainers#24](https://github.com/devcontainers/cli/pull/24) @chrmarti
- [ ] :runner: Discuss community contribution plans [devcontainers/spec/pull#40](https://github.com/devcontainers/spec/pull/40) @bamurtaugh @chrmarti

### Remote-WSL
- None.

----
### Deferred
- [ ] Add `code` CLI argument to open folder in container using remote containers extension [vscode-remote-release#6771](https://github.com/microsoft/vscode-remote-release/issues/6771) @chrmarti
- [ ] Move dev container json schema out of vscode repo and publish/consume it via `schemastore.org` [devcontainers/spec#14](https://github.com/devcontainers/spec/issues/14) @chrmarti

**Comment by joshspicer** [comment]
> Move dev container json schema out of vscode repo and publish/consume it via schemastore.org @chrmarti

We should also publish the schema for `devcontainer-feature.json`, as we're getting close to accepting the initial proposal (https://github.com/devcontainers/spec/blob/main/proposals/devcontainer-features.md#devcontainer-featurejson-properties).  This will assist/welcome community members to author their own features.

If there is an approval process with schemastore.org, perhaps it makes sense to batch our submissions.
