### ISSUE TITLE
Remote: Iteration Plan for July 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#6919]
This plan captures our work in **July**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/154652). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Dev Container Specification / CLI
- [x] Features v2 [devcontainers/cli#73](https://github.com/devcontainers/cli/pull/73) @chrmarti
- [x] Add `features test ...` command [devcontainers/cli#11](https://github.com/devcontainers/cli/pull/11) @chrmarti
- [x] Add `description` property to a feature [devcontainers/cli#58](https://github.com/devcontainers/cli/pull/58) @chrmarti
- [x] Support multiple `--image-name` parameters [devcontainers/cli#61](https://github.com/devcontainers/cli/pull/61) @chrmarti
- [x] Move dev container json schema out of vscode repo and publish/consume it via `schemastore.org` [devcontainers/spec#14](https://github.com/devcontainers/spec/issues/14) @aeschli @chrmarti
- [x] Update CLI docs [vscode-docs#5436](https://github.com/microsoft/vscode-docs/issues/5436) @bamurtaugh @gregvanl
- [ ] :runner: Discuss community contribution plans [devcontainers/spec/pull#40](https://github.com/devcontainers/spec/pull/40) @bamurtaugh @chrmarti

----
### Deferred
- [ ] Install a feature more than once [devcontainers/spec#44](https://github.com/devcontainers/spec/issues/44) @chrmarti
- [ ] Replace old devcontainer CLI with new CLI in path [vscode-remote-release#6859](https://github.com/microsoft/vscode-remote-release/issues/6859) @chrmarti
- [ ] Add `code` CLI argument to open folder in container using remote containers extension [vscode-remote-release#6771](https://github.com/microsoft/vscode-remote-release/issues/6771) @chrmarti
