### ISSUE TITLE
Remote: Iteration Plan for September 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#7160]
This plan captures our work in **September**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/160046). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Dev Container Specification / CLI
- [x] Dev container metadata in image labels [devcontainers/spec#18](https://github.com/devcontainers/spec/issues/18) @chrmarti
- [ ] :runner: Unique ID into volume mount names [devcontainers/spec#62](https://github.com/devcontainers/spec/issues/62) @chrmarti
- [x] devcontainer-lock.json proposal [devcontainers/spec#101](https://github.com/devcontainers/spec/pull/101) @chrmarti
- [x] Discuss community contribution plans [devcontainers/spec#71](https://github.com/devcontainers/spec/issues/71) @bamurtaugh @chrmarti
- [ ] :red_circle: :muscle: "Create a Dev Container" without needing a folder @chrmarti
- [x] Documentation changes from latest dev container updates [vscode-docs#5593](https://github.com/microsoft/vscode-docs/issues/5593) @bamurtaugh

----
### Deferred
- [ ] :muscle: Handle Cygwin / Git Bash sockets forwarding on Windows [devcontainers/cli#82](https://github.com/devcontainers/cli/pull/82) @chrmarti
