### ISSUE TITLE
Remote: Iteration Plan for October 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#7315]
This plan captures our work in **October**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/163069). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- [x] Allow resolvers to signal a fatal failure during the initial connection [vscode#162590](https://github.com/microsoft/vscode/issues/162590) @alexdima

### Dev Containers Extension
- [x] "Create a Dev Container" without needing a folder [vscode-remote-release#7363](https://github.com/microsoft/vscode-remote-release/issues/7363) @chrmarti

### Dev Container Specification / CLI
- [x] Make it easier for features to see which user is the remoteUser [devcontainers/spec#91](https://github.com/devcontainers/spec/issues/91) @chrmarti
- [x] Unique ID into volume mount names [devcontainers/spec#62](https://github.com/devcontainers/spec/issues/62) @chrmarti

### WSL
- [ ] :muscle: Download server bits when updating and WSL was used recently [vscode-remote-release#3839](https://github.com/microsoft/vscode-remote-release/issues/3839)@aeschli

### Remote-SSH
- [ ] :runner: Improvements to SSH config file parsing/writing [vscode-remote-release#7321](https://github.com/microsoft/vscode-remote-release/issues/7321) @eleanorjboyd @roblourens
- [ ] :hand: Support new fatal failure workflow [vscode#163241](https://github.com/microsoft/vscode/issues/163241) @eleanorjboyd @roblourens

----
### Deferred
- [ ] Fix port error message regression [vscode-remote-release#5970](https://github.com/microsoft/vscode-remote-release/issues/5970) @eleanorjboyd @roblourens
