### ISSUE TITLE
Remote: Iteration Plan for November 2022

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#7479]
This plan captures our work in **November**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/165643). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Dev Container Specification / CLI
- [x] GPU requirement PR [devcontainers/cli#173](https://github.com/devcontainers/cli/pull/173) @chrmarti
- [x] Handle Cygwin / Git Bash sockets forwarding on Windows PR [devcontainers/cli#82](https://github.com/devcontainers/cli/pull/82) @chrmarti
- [x] Bundle `@devcontainers/cli` [devcontainers/cli#279](https://github.com/devcontainers/cli/issues/279) @chrmarti
- [x] Consume bundled `@devcontainers/cli` [vscode-remote-release#7508](https://github.com/microsoft/vscode-remote-release/issues/7508) @chrmarti

### Dev Containers Extension
- [x] Polish "Create Dev Container..." flow [vscode-remote-release#7461](https://github.com/microsoft/vscode-remote-release/issues/7461) @chrmarti
- [ ] :runner: Full support for folders with multiple devcontainer.json files [vscode-remote-release#7548](https://github.com/microsoft/vscode-remote-release/issues/7548) @chrmarti
- [ ] :muscle: :red_circle: Take advantage of container metadata when attaching @chrmarti

### WSL
- [ ] :muscle: Download server bits when updating and WSL was used recently [vscode-remote-release#3839](https://github.com/microsoft/vscode-remote-release/issues/3839)@aeschli

### Remote-SSH
- [x] Improvements to SSH config file parsing/writing [vscode-remote-release#7321](https://github.com/microsoft/vscode-remote-release/issues/7321) @eleanorjboyd @roblourens
- [x] Surface error to user if no available ports exist [vscode-remote-release#5970](https://github.com/microsoft/vscode-remote-release/issues/5970) @eleanorjboyd @roblourens
- [ ] :runner: Adopt new error type in SSH resolver [vscode#163241](https://github.com/microsoft/vscode/issues/163241) @eleanorjboyd @roblourens
- [ ] :muscle: Attempt reconnection following device short sleep [vscode-remote-release#5755](https://github.com/microsoft/vscode-remote-release/issues/5755) @eleanorjboyd @roblourens

### Remote-Tunnel
- [x] Compress data over the websocket: [vscode#163688](https://github.com/microsoft/vscode/issues/163688) @connor4312
- [x] NixOS compatibility: [vscode-remote-release#7129](https://github.com/microsoft/vscode-remote-release/issues/7129) @connor4312
- [ ] :runner: Prevent sleep: [vscode-remote-release#7125](https://github.com/microsoft/vscode-remote-release/issues/7125) @connor4312
- [x] 'local download' mode: [vscode-remote-release#6959](https://github.com/microsoft/vscode-remote-release/issues/6959) @connor4312

----
### Deferred
- None.
