### ISSUE TITLE
Remote: Iteration Plan for January 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#7783]
This plan captures our work in **January**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/170413). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Dev Container Specification / CLI
- [x] Update schema to equivalent of inlining `allOf` [devcontainers/spec#93](https://github.com/devcontainers/spec/issues/93) @aeschli @chrmarti

### Core
- [x] Rethink and clean-up contributions to the remote indicator [vscode-remote-release#7741](https://github.com/microsoft/vscode-remote-release/issues/7741) @aeschli @chrmarti @eleanorjboyd @joyceerhl
- [x] Create a new devcontainer.json for the vscode repository that is simpler [vscode#170969](https://github.com/microsoft/vscode/issues/170969) @chrmarti

### Dev Containers Extension
- [ ] :runner: Full support for folders with multiple devcontainer.json files [vscode-remote-release#7548](https://github.com/microsoft/vscode-remote-release/issues/7548) @chrmarti
- [x] Hint to rebuild container after adding a feature [vscode-remote-release#7592](https://github.com/microsoft/vscode-remote-release/issues/7592) @chrmarti
- [x] Polish "Create Dev Container..." [vscode-remote-release#7629](https://github.com/microsoft/vscode-remote-release/issues/7629) @chrmarti
- [x] Investigate docker credential forwarding [vscode-remote-release#7184](https://github.com/microsoft/vscode-remote-release/issues/7184) @chrmarti
- [ ] :runner: Take advantage of container metadata when attaching [vscode-remote-release#7872](https://github.com/microsoft/vscode-remote-release/issues/7872) @chrmarti
- [ ] :muscle: :red_circle: Indicate that bind mounts are slower (on Windows) in the Remote Explorer info tree view @chrmarti

### WSL
- [ ] :muscle: Download server bits when updating and WSL was used recently [vscode-remote-release#3839](https://github.com/microsoft/vscode-remote-release/issues/3839) @aeschli
- [ ] :runner: Explore adopting the CLI for starting/managing the VS Code Server on WSL [vscode-remote-release#7864](https://github.com/microsoft/vscode-remote-release/issues/7864) @aeschli @connor4312

### Remote-SSH
- [ ] :runner: Adopt new error type in SSH resolver [vscode#163241](https://github.com/microsoft/vscode/issues/163241) @eleanorjboyd @roblourens
- [ ] :muscle: Attempt reconnection following device short sleep [vscode-remote-release#5755](https://github.com/microsoft/vscode-remote-release/issues/5755) @eleanorjboyd @roblourens
- [ ] :muscle: Find workaround for new Windows bug [vscode-remote-release#7272](https://github.com/microsoft/vscode-remote-release/issues/7272) @eleanorjboyd

### Remote-Tunnel
- [x] Prevent sleep: [vscode-remote-release#7125](https://github.com/microsoft/vscode-remote-release/issues/7125) @connor4312
- [ ] :muscle: Support "Allow Tunnel access" for the remote when connected to a SSH/WSL remote window [vscode-remote-release#7865](https://github.com/microsoft/vscode-remote-release/issues/7865) @aeschli @connor4312
- [x] Improve reconnection reliability [vscode-remote-tunnels#565](https://github.com/microsoft/vscode-remote-tunnels/issues/565)  [vscode-remote-tunnels#569](https://github.com/microsoft/vscode-remote-tunnels/issues/569) @connor4312
- [ ] :runner: CLI invocations should connect to the running CLI process [vscode#171520](https://github.com/microsoft/vscode/issues/171520) @connor4312 @aeschli

----
### Deferred
- [ ] Adopt CLI service mode in "Turn on Remote Tunnel Access" [vscode#171520](https://github.com/microsoft/vscode/issues/171520) @aeschli
