### ISSUE TITLE
Remote: Iteration Plan for February 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#7972]
This plan captures our work in **February 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/173445). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- [x] Simplify content in the remote indicator [vscode-internalbacklog#3440](https://github.com/microsoft/vscode-internalbacklog/issues/3440) @joyceerhl @daviddossett @chrmarti @aeschli @connor4312 @eleanorjboyd @jkeech @bamurtaugh

### Dev Container Specification / CLI
- [ ] :runner: Remove dependance on legacy features [cli#287](https://github.com/devcontainers/cli/issues/287) @chrmarti
- [x] Setting `NODE_OPTIONS` in `remoteEnv` breaks Codespace ⚠️  [cli#351](https://github.com/devcontainers/cli/issues/351) @chrmarti

### Dev Containers Extension
- [ ] :runner: Remove dependance on built-in repository configs [vscode-remote-release#7532](https://github.com/microsoft/vscode-remote-release/issues/7532) @chrmarti
- [x] Indicate that bind mounts are slower (on Windows) in the Remote Explorer info tree view [vscode-remote-release#8014](https://github.com/microsoft/vscode-remote-release/issues/8014) @chrmarti
- [ ] :muscle: Attach to Kubernetes: Support container metadata [vscode-remote-release#7880](https://github.com/microsoft/vscode-remote-release/issues/7880) @chrmarti

### WSL
- [x] Download server bits when updating and WSL was used recently [vscode-remote-release#3839](https://github.com/microsoft/vscode-remote-release/issues/3839) @aeschli
- [ ] :runner: Explore adopting the CLI for starting/managing the VS Code Server on WSL [vscode-remote-release#7864](https://github.com/microsoft/vscode-remote-release/issues/7864) @aeschli @connor4312

### Remote-SSH
- [x] Stop Retry on Fatal Failures [vscode-remote-release#7498](https://github.com/microsoft/vscode-remote-release/issues/7498) @eleanorjboyd @roblourens
- [ ] :muscle: Attempt reconnection following device short sleep [vscode-remote-release#5755](https://github.com/microsoft/vscode-remote-release/issues/5755) @eleanorjboyd @roblourens
- [ ] :runner: Find workaround for new Windows bug [vscode-remote-release#7272](https://github.com/microsoft/vscode-remote-release/issues/7272) @eleanorjboyd

### Remote Repositories
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/25) @joyceerhl
- [x] Explore Git LFS support [vscode-remote-repositories-github#7](https://github.com/microsoft/vscode-remote-repositories-github/issues/7) @joyceerhl
- [x] Ship Remote Repositories Getting Started walkthrough [vscode-remote-repositories-github#268](https://github.com/microsoft/vscode-remote-repositories-github/issues/269) @bhavyaus @joyceerhl 

----

### Deferred
- [ ] Improve management of Dev Containers [vscode-remote-release#7720](https://github.com/microsoft/vscode-remote-release/issues/7720) @chrmarti
- [ ] Fix password prompt on folder open [vscode-remote-release#6227](https://github.com/microsoft/vscode-remote-release/issues/6227) @eleanorjboyd
- [ ] CLI invocations should connect to the running CLI process [vscode#171520](https://github.com/microsoft/vscode/issues/171520) @connor4312 @aeschli
- [ ] Support "Allow Tunnel access" for the remote when connected to a SSH/WSL remote window [vscode-remote-release#7865](https://github.com/microsoft/vscode-remote-release/issues/7865) @aeschli @connor4312
- [ ] Adopt CLI service mode in "Turn on Remote Tunnel Access" [vscode#171520](https://github.com/microsoft/vscode/issues/171520) @aeschli
- [ ] :red_circle: Adopt the CLI RPC library in the test resolver extension @aeschli (requires open-sourcing the cli-rpc library)
