### ISSUE TITLE
Remote: Iteration Plan for March 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#8139]
This plan captures our work in **March 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/176147). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Dev Container Specification / CLI
- [x] :muscle: Transform maven, gradle and jupyterlab usages to their features v2 counterparts [cli#461](https://github.com/devcontainers/cli/issues/461) @chrmarti

### Dev Containers Extension
- [x] Remove dependance on built-in repository configs [vscode-remote-release#7532](https://github.com/microsoft/vscode-remote-release/issues/7532) @chrmarti
- [x] Improve management of Dev Containers [vscode-remote-release#7720](https://github.com/microsoft/vscode-remote-release/issues/7720) @chrmarti
- [ ] :muscle: Attach to Kubernetes: Support container metadata [vscode-remote-release#7880](https://github.com/microsoft/vscode-remote-release/issues/7880) @chrmarti

### Remote-SSH
- [x] Refresh recently used folders when making edits in other windows [vscode-remote-release#8100](https://github.com/microsoft/vscode-remote-release/issues/8100) @eleanorjboyd

### Remote Repositories
- [ ] :runner: Support committing Git LFS files from web [vscode-remote-repositories-github#7](https://github.com/microsoft/vscode-remote-repositories-github/issues/7) @joyceerhl
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/26) @joyceerhl
- [x] :muscle: Support `.gitignore` [vscode#172643](https://github.com/microsoft/vscode/issues/172643) @joyceerhl

### Remote-Tunnel
- [x] CLI invocations should connect to the running CLI process [vscode#171520](https://github.com/microsoft/vscode/issues/171520) @connor4312
- [x] Adopt CLI service mode in "Turn on Remote Tunnel Access" [vscode#171520](https://github.com/microsoft/vscode/issues/171520) @aeschli
- [x] Allow to open vscode desktop when connected to a tunnel on vscode.dev [vscode-remote-release#8199](https://github.com/microsoft/vscode-remote-release/issues/8199) @aeschli

----

### Deferred
- [ ] Fix password prompt on folder open [vscode-remote-release#6227](https://github.com/microsoft/vscode-remote-release/issues/6227) @eleanorjboyd @roblourens
- [ ] Attempt reconnection following device short sleep [vscode-remote-release#5755](https://github.com/microsoft/vscode-remote-release/issues/5755) @eleanorjboyd
- [ ] Reload remote explorer when editing ssh config [vscode-remote-release#7144](https://github.com/microsoft/vscode-remote-release/issues/7144) @eleanorjboyd
- [ ] Support "Allow Tunnel access" for the remote when connected to a SSH/WSL remote window [vscode-remote-release#7865](https://github.com/microsoft/vscode-remote-release/issues/7865) @aeschli @connor4312
- [x] Explore adopting the CLI for starting/managing the VS Code Server on WSL [vscode-remote-release#7864](https://github.com/microsoft/vscode-remote-release/issues/7864) @aeschli @connor4312
