### ISSUE TITLE
Remote: Iteration Plan for April 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#8314]
This plan captures our work in **April 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/178951). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- [ ] :runner: Improvements to the Remote Explorer [vscode#178854](https://github.com/microsoft/vscode/issues/178854) @joyceerhl

### Dev Container Specification / CLI
- None.

### Dev Containers Extension
- [x] Implement DevContainer Lockfile @chrmarti [vscode-remote-release#8330](https://github.com/microsoft/vscode-remote-release/issues/8330)
- [ ] :muscle: Attach to Kubernetes: Support container metadata [vscode-remote-release#7880](https://github.com/microsoft/vscode-remote-release/issues/7880) @chrmarti

### Remote-SSH
- None.

### WSL
- [ ] :runner: Explore adopting the CLI for starting/managing the VS Code Server on WSL [vscode-remote-release#7864](https://github.com/microsoft/vscode-remote-release/issues/7864) @connor4312 @aeschli

### Remote Repositories
- [x] Support committing Git LFS files from web [vscode-remote-repositories-github#7](https://github.com/microsoft/vscode-remote-repositories-github/issues/7) @joyceerhl
- [x] Break Remote Repositories extension's dependency on the git-base extension [vscode#177944](https://github.com/microsoft/vscode/issues/177944) @joyceerhl
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/29) @joyceerhl

### Remote-Tunnel
- [ ] :runner: Support applying VS Code updates while the CLI is running in service mode [vscode#177226](https://github.com/microsoft/vscode/issues/177226) @aeschli @joaomoreno

----

### Deferred
- [ ] Investigate more graceful disconnection [vscode#173603](https://github.com/microsoft/vscode/pull/173603) @aeschli
- [ ] Fix password prompt on folder open [vscode-remote-release#6227](https://github.com/microsoft/vscode-remote-release/issues/6227) @eleanorjboyd @roblourens
- [ ] Attempt reconnection following device short sleep [vscode-remote-release#5755](https://github.com/microsoft/vscode-remote-release/issues/5755) @eleanorjboyd
- [ ] Reload remote explorer when editing ssh config [vscode-remote-release#7144](https://github.com/microsoft/vscode-remote-release/issues/7144) @eleanorjboyd
