### ISSUE TITLE
Remote: Iteration Plan for May 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#8455]
This plan captures our work in **May 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/181778). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- [x] Improvements to Remote Explorer [vscode-remote-release#8397](https://github.com/microsoft/vscode-remote-release/issues/8397) @joyceerhl @chrmarti @aeschli @connor4312 @roblourens
- [x] Allow Remote Resolver extensions to be web extensions [vscode#183267](https://github.com/microsoft/vscode/issues/183267) @connor4312 @aeschli
- [x] Allow users to quickly make port public after discovery on web [vscode-remote-release#8442](https://github.com/microsoft/vscode-remote-release/issues/8442) @alexr00
- [ ] :hand: Configure a port as public in `portsAttributes` [vscode-remote-release#6363](https://github.com/microsoft/vscode-remote-release/issues/6363) @alexr00

### Dev Container Specification / CLI
- None.

### Dev Containers Extension
- [ ] :muscle: Attach to Kubernetes: Support container metadata [vscode-remote-release#7880](https://github.com/microsoft/vscode-remote-release/issues/7880) @chrmarti

### Remote-SSH
- None.

### WSL
- [x] Provide a WSL Resolver web extension [vscode-remote-release#8518](https://github.com/microsoft/vscode-remote-release/issues/8518)@aeschli
- [x] Explore adopting the CLI for starting/managing the VS Code Server on WSL [vscode-remote-release#7864](https://github.com/microsoft/vscode-remote-release/issues/7864) @connor4312 @aeschli

### Remote Repositories
- [x] Allow checking out branches on `vscode.dev` from the branch picker [vscode#176333](https://github.com/microsoft/vscode/issues/176333) @joyceerhl @lszomoru
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/28) @joyceerhl

### Remote-Tunnel
- [x] Adopt Remote Resolvers in the Remote-Tunnel web extension [vscode-remote-tunnels#633](https://github.com/microsoft/vscode-remote-tunnels/issues/633) @connor4312
- [x] Support applying VS Code updates while the CLI is running in service mode [vscode#177226](https://github.com/microsoft/vscode/issues/177226) @aeschli @connor4312
- [x] Provide end-to-end smoke tests for Remote-Tunnel [vscode-remote-tunnels#625](https://github.com/microsoft/vscode-remote-tunnels/issues/625) @connor4312

----

### Deferred
- [ ] Fix password prompt on folder open [vscode-remote-release#6227](https://github.com/microsoft/vscode-remote-release/issues/6227) @eleanorjboyd @roblourens
- [ ] Attempt reconnection following device short sleep [vscode-remote-release#5755](https://github.com/microsoft/vscode-remote-release/issues/5755) @eleanorjboyd
- [ ] Reload remote explorer when editing ssh config [vscode-remote-release#7144](https://github.com/microsoft/vscode-remote-release/issues/7144) @eleanorjboyd
