### ISSUE TITLE
Remote: Iteration Plan for June 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#8593]
This plan captures our Remote work in **June 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/184844). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- [x] Decouple nested `Resolvers` [vscode#184171](https://github.com/microsoft/vscode/issues/184171) @connor4312

### Dev Container Specification / CLI
- [x] Update .NET dev container resources to work well with C# Dev Kit [devcontainers#164](https://github.com/devcontainers/templates/issues/164) @bamurtaugh
- [ ] :runner: Record feature dependencies in the lockfile [devcontainers/cli#564](https://github.com/devcontainers/cli/issues/564) @chrmarti
- [x] Make it easy to update to newer versions of features (codelenses, CLI command, diagnostics) [vscode-remote-release#8640](https://github.com/microsoft/vscode-remote-release/issues/8640) @chrmarti

### Dev Containers Extension
- [ ] Explore helping to install docker inside WSL [vscode-remote-release#8641](https://github.com/microsoft/vscode-remote-release/issues/8641) @chrmarti

### Remote-SSH
- None.

### WSL
- [x] Make it easier to access WSL directly from vscode.dev [vscode-dev#919](https://github.com/microsoft/vscode-dev/issues/919) @connor4312
- [x] Support WSL over tunnels on desktop [vscode#184664](https://github.com/microsoft/vscode/issues/184664) @connor4312

### Remote-Tunnel
- [ ] :runner: Enable starting tunnel service from UI [vscode#184663](https://github.com/microsoft/vscode/issues/184663) @connor4312

### Remote Repositories
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/32) @joyceerhl

----

### Deferred
- :muscle: Attach to Kubernetes: Support container metadata [vscode-remote-release#7880](https://github.com/microsoft/vscode-remote-release/issues/7880) @chrmarti
