### ISSUE TITLE
[WSL Bug]: reveal explorer is not working wsl

### ISSUE THREAD

**Issue by cedric05** [microsoft/vscode-remote-release#8599]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [ ] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### ->

Reveal in explorer is not working, where as it used to work in earlier version of vscode/remote-wsl, 
![image](https://github.com/microsoft/vscode-remote-release/assets/11557066/218d5b3f-e26d-4f89-aaf9-7c53547f3e1f)

### Expected Behavior

It should open in exploer 

### Steps To Reproduce

1. connect to wsl
2. in editor panel, right click and select `reveal in explorer`

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

```[tasklist]
### Tasks
```

**Comment by Levdbas** [comment]
I am running into the same problem. Running on Windows 11, WSL extention v0.79.5. If I can provide further information, please let me know.

**Comment by bamurtaugh** [comment]
Thank you for filing!

I don't see the browser error, but nothing happens for me either when I try "Reveal in Explorer," cc @aeschli

**Comment by suicideDuck22** [comment]
When this issue has been created, I had the same problem.
(On the v0.79.4).
This problem seems resolved on v0.79.5.

**Comment by Levdbas** [comment]
This is fixed for me as well on Windows 11, extension version v0.79.5 (win11, wsl2)

**Comment by bamurtaugh** [comment]
Thanks all! Since it sounds like this is now resolved, I'll close out this issue, but please let us know if you encounter it again.
