### ISSUE TITLE
[Remote-SSH Bug]: 

### ISSUE THREAD

**Issue by Sham9373** [microsoft/vscode-remote-release#8633]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### Required Troubleshooting Steps

- [X] I have followed these troubleshooting steps
- [X] I have tried both values of the `remote.SSH.useLocalServer` setting

### Connect Locally

It connects successfully

### Remote-SSH Log

<details>
<summary>Remote-SSH Log</summary>
<p>

```
[PASTE LOG HERE]
```

</p>
</details>

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8454
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8631
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8632
- [ ] https://github.com/microsoft/vscode-remote-release/issues/3319
```

**Comment by Sham9373** [comment]
Helo

**Comment by Sham9373** [comment]
No comments

**Comment by Sham9373** [comment]
`hellow` you
