### ISSUE TITLE
Remote: Iteration Plan for July 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#8694]
This plan captures our Remote work in **July 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/187398). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- None.

### Dev Container Specification / CLI
- [x] Remove `node-pty` dependency from `@devcontainers/cli` [vscode-remote-release#8698](https://github.com/microsoft/vscode-remote-release/issues/8698) @chrmarti
- [x] Record feature dependencies in the lockfile [devcontainers/cli#564](https://github.com/devcontainers/cli/issues/564) @chrmarti
- [ ] :runner: Update dev container docs and Templates on prebuilds [devcontainers/spec/issues/261](https://github.com/devcontainers/spec/issues/261), [vscode-internalbacklog/issues/4456](https://github.com/microsoft/vscode-internalbacklog/issues/4456) @bamurtaugh

### Dev Containers Extension
- [ ] Explore helping to install docker inside WSL [vscode-remote-release#8641](https://github.com/microsoft/vscode-remote-release/issues/8641) @chrmarti

### Remote-SSH
- [ ] :muscle: :runner: Explore an exec server implementation of the SSH resolver [vscode-remote-release#8747](https://github.com/microsoft/vscode-remote-release/issues/8747) @connor4312

### WSL
- None.

### Remote-Tunnel
- [x] Enable starting tunnel service from UI [vscode#184663](https://github.com/microsoft/vscode/issues/184663) @connor4312
- [x] Notify users when reaching their dev tunnels quotas [vscode#187649](https://github.com/microsoft/vscode/issues/187649) @connor4312
- [ ] :runner: :hand: Support AAD auth for dev tunnels [vscode-internalbacklog#4383](https://github.com/microsoft/vscode-internalbacklog/issues/4383) @connor4312
- [ ] :runner: Support forwarding local ports using dev tunnels [vscode-internalbacklog#4382](https://github.com/microsoft/vscode-internalbacklog/issues/4382) @alexr00 @connor4312

### Remote Repositories
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/33) @joyceerhl

----

### Deferred
- None.
