### ISSUE TITLE
Remote: Iteration Plan for August 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#8807]
This plan captures our Remote work in **August 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/189778). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Core
- None.

### Dev Container Specification / CLI
- [x] Update dev container docs and Templates on prebuilds [devcontainers/spec/issues/261](https://github.com/devcontainers/spec/issues/261), [vscode-internalbacklog/issues/4456](https://github.com/microsoft/vscode-internalbacklog/issues/4456) @bamurtaugh

### Dev Containers Extension
- [x] Explore helping to install docker inside WSL [vscode-remote-release#8641](https://github.com/microsoft/vscode-remote-release/issues/8641) @chrmarti

### Remote-SSH
- [x] Roll-out exec server implementation of the SSH resolver [vscode-remote-release#8747](https://github.com/microsoft/vscode-remote-release/issues/8747) @connor4312

### WSL
- [x] Support WSL over SSH (on WSL2 pre-release) [vscode-remote-release#8747](https://github.com/microsoft/vscode-remote-release/issues/8747) @connor4312

### Remote-Tunnel
- [ ] :hand: :runner: Support AAD auth for dev tunnels @connor4312
- [x] Support local port privacy options [vscode#189677](https://github.com/microsoft/vscode/issues/189677) @connor4312
- [x] Local port forwarding should be built-in [vscode#189678](https://github.com/microsoft/vscode/issues/189678) @connor4312
- [x] Local port forwarding should notify about resource usage limits [vscode#189679](https://github.com/microsoft/vscode/issues/189679) @connor4312
- [x] Auto forwarded ports should be restored [vscode-remote-release#8638](https://github.com/microsoft/vscode-remote-release/issues/8638) @alexr00

### Remote Repositories
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/36) @joyceerhl

----

### Deferred
- None.

**Comment by SimSeeker** [comment]
So whom will I be working for Microsoft?
