### ISSUE TITLE
Remote: Iteration Plan for September 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#8955]
This plan captures our Remote work in **September 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22September+2023%22). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Dev Container Specification / CLI
- [x] Explore standardizing on new spec format like Bikeshed [devcontainers/spec#293](https://github.com/devcontainers/spec/issues/293) @bamurtaugh

### Dev Containers Extension
- [ ] :runner: Support connecting to docker containers over tunnels [vscode-remote-release#7705](https://github.com/microsoft/vscode-remote-release/issues/7705) @chrmarti @connor4312
- [ ] :runner: Support archiving the vscode-dev-containers repo @chrmarti [vscode-remote-release#8994](https://github.com/microsoft/vscode-remote-release/issues/8994)

### Remote Repositories
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/38) @joyceerhl

----

### Deferred
- None.
