### ISSUE TITLE
pro

### ISSUE THREAD

**Issue by protection6** [microsoft/vscode-remote-release#9044]
Type: <b>Bug</b>

load_training

Extension version: 0.314.0
VS Code version: Code 1.82.2 (abd2f3db4bdb28f9e95536dfa84d8479f1eb312d, 2023-09-14T05:55:25.390Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3600 6-Core Processor               (12 x 3593)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.95GB (5.79GB free)|
|Process Argv|C:\\Users\\PC\\AppData\\Local\\ms-vscode.cpptools-1.17.5@linux-x64.vsix --crash-reporter-id ef19e6b5-1e41-45bb-8401-96c99d2d64fc|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
py29gd2263cf:30792227
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
showlangstatbar:30737416
03d35959:30757346
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
synctok:30821570
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015:30845448
pythonfb280951:30830810

```

</details>

```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8638
- [ ] https://github.com/microsoft/vscode-remote-release/issues/937
- [ ] https://github.com/microsoft/vscode-remote-release/issues/512
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8878
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9026
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8920
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9031
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8926
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9043
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9042
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8924
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9041
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9023
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9016
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9040
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8994
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9039
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8834
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9025
- [ ] https://github.com/microsoft/vscode-remote-release/issues/7284
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9036
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8998
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9007
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9038
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8422
- [ ] https://github.com/microsoft/vscode-remote-release/issues/8824
- [ ] https://github.com/microsoft/vscode-remote-release/issues/9037
```

**Comment by bamurtaugh** [comment]
If you have a specific issue, please let us know. Thanks!
