### ISSUE TITLE
Remote: Iteration Plan for October 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#9078]
This plan captures our Remote work in **October 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22October+2023%22). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| 🏃‍♀️                  | work in progress                                  |
| ✋                  | blocked task                                      |
| 💪                  | stretch goal for this iteration                   |
| 🔴                  | missing issue reference                           |
| 🔵                  | more investigation required to remove uncertainty |
| ⚫                  | under discussion within the team                  |
| ⬛                  | a large work item, larger than one iteration      |

</details>

### Dev Container Specification / CLI
- [x] Next steps on dev container website and spec format standardization [devcontainers/spec#293](https://github.com/devcontainers/spec/issues/293) @bamurtaugh

### Dev Containers Extension
- [x] Support connecting to docker containers over tunnels [vscode-remote-release#9095](https://github.com/microsoft/vscode-remote-release/issues/9095) @chrmarti @connor4312
- [ ] :runner: Support archiving the vscode-dev-containers repo [vscode-remote-release#8994](https://github.com/microsoft/vscode-remote-release/issues/8994) @chrmarti

### SSH Extension
- [ ] :runner: Roll-out exec server implementation [vscode-remote-release#9077](https://github.com/microsoft/vscode-remote-release/issues/9077) @connor4312

### Tunnels
- [x] Support AAD auth for dev tunnels [vscode-remote-release#8908](https://github.com/microsoft/vscode-remote-release/issues/8908) @connor4312

### Remote Repositories
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/42) @joyceerhl

----

### Deferred
- None.
