### ISSUE TITLE
Remote: Iteration Plan for July 2019

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#916]
This plan captures our work on the Remote development extensions in **July**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues/76735). Although we plan for a whole iteration, we not only ship at the end of an iteration but throughout.

We'll focus on stability, improving the first time user experience, and overall polishing.

## Plan Items

Below is a summary of the top level plan items.

Legend of annotations:

| Mark                | Description                                       |
| ------------------- | ------------------------------------------------- |
| :runner:            | work in progress                                  |
| :hand:              | blocked task                                      |
| :muscle:            | stretch goal for this iteration                   |
| :red_circle:        | missing issue reference                           |
| :large_blue_circle: | more investigation required to remove uncertainty |
| :black_circle:      | under discussion within the team                  |

### Remote - Core
- [x] Align presentation of empty workbench on startup with SSH (show explorer if not visible, show terminal) https://github.com/microsoft/vscode-remote-release/issues/954 @aeschli
- [x] Add command 'Install locally installed extensions' that supports to selectively install workspace extensions into the https://github.com/microsoft/vscode-remote-release/issues/157 remote @sandy081
- [x] Bring `Open In Terminal` to Remote https://github.com/microsoft/vscode-remote-release/issues/774 @tyriar

### Remote - SSH
- [x] Explore support for `SSH Agent` forwarding https://github.com/microsoft/vscode-remote-release/issues/16 @roblourens
- [x] Explore further improvements to password authentication https://github.com/microsoft/vscode-remote-release/issues/642 @roblourens
- [x] Explore connection sharing between windows that connect to the same host https://github.com/microsoft/vscode-remote-release/issues/96 @roblourens
- [x] Explore installing the VS Code server through the VS Code client https://github.com/microsoft/vscode-remote-release/issues/15 @roblourens

### Remote - WSL
- [x] Tune polling file watcher work around for WSL1 https://github.com/microsoft/vscode-remote-release/issues/953 @aeschli
- [x] Support the Alpine distro https://github.com/microsoft/vscode-remote-release/issues/952 @aeschli
- [ ] :runner: WSL Blog post series @chrisdias

### Extension Contributions
- [x] Add a VS Code Remote integration for the [Peacock](https://marketplace.visualstudio.com/items?itemName=johnpapa.vscode-peacock) extension https://github.com/johnpapa/vscode-peacock/pull/187 @egamma

-------
### Deferred Items
- :runner: Add commands 'Open Workspace in Container', 'Reopen Workspace in Container' https://github.com/microsoft/vscode-remote-release/issues/387 @aeschli
- Generalize SSH explorer to allow contributions from Containers and WSL https://github.com/microsoft/vscode-remote-release/issues/926 @kieferrm
- Investigate reconnect reliability https://github.com/microsoft/vscode-remote-release/issues/955 @alexandrudima

**Comment by WSLUser** [comment]
> 🔴 Explore installing the VS Code server through the VS Code client

https://github.com/microsoft/vscode-remote-release/issues/15
