### ISSUE TITLE
Remote: Iteration Plan for November 2023

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#9169]
This plan captures our Remote work in **November 2023**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22November+2023%22). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark | Description                                       |
| ---- | ------------------------------------------------- |
| 🏃‍♀️   | work in progress                                  |
| ✋   | blocked task                                      |
| 💪   | stretch goal for this iteration                   |
| 🔴   | missing issue reference                           |
| 🔵   | more investigation required to remove uncertainty |
| ⚫   | under discussion within the team                  |
| ⬛   | a large work item, larger than one iteration      |

</details>

### Core

- [x] Proxy: send local CAs to WSL/devcontainers when `--use-host-proxy` is used [vscode-remote-release#9176](https://github.com/microsoft/vscode-remote-release/issues/9176) @chrmarti

### Dev Container Specification / CLI

- [x] Add option to opt out of extensions [vscode-remote-release#9177](https://github.com/microsoft/vscode-remote-release/issues/9177) @chrmarti
- [x] Review extensions that are part of base images [vscode-remote-release#9174](https://github.com/microsoft/vscode-remote-release/issues/9174) @chrmarti

### Dev Containers Extension

- [x] Support archiving the vscode-dev-containers repo [vscode-remote-release#8994](https://github.com/microsoft/vscode-remote-release/issues/8994) @chrmarti
- [x] Automatically install useful workspace extensions in devcontainers if they are installed locally [vscode-remote-release#9173](https://github.com/microsoft/vscode-remote-release/issues/9173) @chrmarti
- [ ] Explore being able to open a folder in a dev container without a devcontainer.json [vscode-remote-release#9175](https://github.com/microsoft/vscode-remote-release/issues/9175) @chrmarti

### SSH Extension

- [ ] :runner: Roll-out exec server implementation [vscode-remote-release#9077](https://github.com/microsoft/vscode-remote-release/issues/9077) @connor4312

### Tunnels

- None.

### Remote Repositories

- [ ] :runner: Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/44) @joyceerhl

---

### Deferred

- None.
