### ISSUE TITLE
Remote: Iteration Plan for January 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#9329]
This plan captures our Remote work in **January 2024**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22December+%2F+January+2024%22). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items
Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark | Description                                       |
| ---- | ------------------------------------------------- |
| 🏃‍♀️   | work in progress                                  |
| ✋   | blocked task                                      |
| 💪   | stretch goal for this iteration                   |
| 🔴   | missing issue reference                           |
| 🔵   | more investigation required to remove uncertainty |
| ⚫   | under discussion within the team                  |
| ⬛   | a large work item, larger than one iteration      |

</details>

### Dev Container Specification / CLI
- [x] Add support for additional build arguments [vscode-remote-release#3545](https://github.com/microsoft/vscode-remote-release/issues/3545) @chrmarti

### Dev Containers Extension
- [x] Explore being able to open a folder in a dev container without a devcontainer.json [vscode-remote-release#9175](https://github.com/microsoft/vscode-remote-release/issues/9175) @chrmarti

### SSH Extension
- [ ] :runner: Roll-out exec server implementation [vscode-remote-release#9077](https://github.com/microsoft/vscode-remote-release/issues/9077) @connor4312

### Remote Repositories
- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/51) @joyceerhl

---

### Deferred
- None.
