### ISSUE TITLE
Remote: Iteration Plan for February 2024

### ISSUE THREAD

**Issue by kieferrm** [microsoft/vscode-remote-release#9492]
This plan captures our Remote work in **February 2024**. We follow the same iteration cycle as [VS Code](https://github.com/microsoft/vscode/issues?q=is%3Aissue+label%3Aiteration-plan+milestone%3A%22February+2024%22). Although we plan for a whole iteration, we may not only ship at the end of an iteration but throughout.

## Plan Items

Below is a summary of the top level plan items.

<details>
<summary>Legend of annotations</summary>

| Mark | Description                                       |
| ---- | ------------------------------------------------- |
| 🏃‍♀️   | work in progress                                  |
| ✋   | blocked task                                      |
| 💪   | stretch goal for this iteration                   |
| 🔴   | missing issue reference                           |
| 🔵   | more investigation required to remove uncertainty |
| ⚫   | under discussion within the team                  |
| ⬛   | a large work item, larger than one iteration      |

</details>

### Dev Container Specification / CLI

- [x] Improvements to community contributions [spec#405](https://github.com/devcontainers/spec/issues/405) @bamurtaugh
  - [x] Add filtering/sorting abilities to containers.dev to help exploration/discovery [devcontainers.github.io/pull/325](https://github.com/devcontainers/devcontainers.github.io/pull/325)
  - [ ] :runner: Implement PR templates / issue forms [devcontainers.github.io#244](https://github.com/devcontainers/devcontainers.github.io/issues/244), [devcontainers.github.io/pull/354](https://github.com/devcontainers/devcontainers.github.io/pull/354)

### SSH Extension

- [x] Roll-out exec server implementation [vscode-remote-release#9077](https://github.com/microsoft/vscode-remote-release/issues/9077) @connor4312

### Remote Repositories

- [x] Improvements to the GitHub Repositories extension [query](https://github.com/microsoft/vscode-remote-repositories-github/milestone/53) @joyceerhl

---

### Deferred

- None.
